//File: CosTSInteroperation.idl
//Part of the Transaction Service

#ifndef _COS_TS_INTEROPERATION_IDL_
#define _COS_TS_INTEROPERATION_IDL_

#ifdef _PRE_3_0_COMPILER_
#include <orb.idl>
#include <IOP.idl>
#include <CosTransactions.idl>
#pragma prefix "omg.org"
#else
import ::CORBA;
import ::IOP;
import ::CosTransactions;
#endif // _PRE_3_0_COMPILER_

module CosTSInteroperation {

#ifndef _PRE_3_0_COMPILER_
	typeprefix CosTSInteroperation "omg.org";
#endif // _PRE_3_0_COMPILER_

	const IOP::ComponentId TAG_TRANSACTION_POLICY=26;

	struct TransactionPolicyComponent {
		CosTransactions::TransactionPolicyValue       tpv;
	};

	const IOP::ComponentId TAG_OTS_POLICY= 31; 

	const IOP::ComponentId TAG_INV_POLICY= 32;
};
#endif // _COS_TS_INTEROPERATION_IDL_
