

class test_hash_i : public POA_test_hash,
		    public PortableServer::RefCountServantBase
{
public:
  inline test_hash_i() {};
  virtual ~test_hash_i() {};
  
  virtual CORBA::Long echoLong00(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong01(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong02(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong03(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong04(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong05(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong06(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong07(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong08(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong09(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong10(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong11(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong12(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong13(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong14(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong15(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong16(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong17(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong18(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong19(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong20(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong21(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong22(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong23(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong24(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong25(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong26(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong27(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong28(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong29(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong30(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong31(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong32(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong33(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong34(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong35(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong36(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong37(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong38(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong39(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong40(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong41(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong42(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong43(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong44(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong45(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong46(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong47(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong48(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong49(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong50(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong51(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong52(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong53(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong54(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong55(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong56(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong57(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong58(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong59(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong60(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong61(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong62(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong63(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong64(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong65(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong66(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong67(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong68(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong69(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong70(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong71(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong72(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong73(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong74(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong75(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong76(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong77(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong78(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong79(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong80(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong81(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong82(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong83(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong84(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong85(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong86(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong87(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong88(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong89(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong90(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong91(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong92(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong93(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong94(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong95(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong96(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong97(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong98(CORBA::Long data){return data;};
  virtual CORBA::Long echoLong99(CORBA::Long data){return data;};

};

