-- ==================================================== --
-- ===  Code automatically generated by IDL to Ada  === --
-- ===  compiler OrbAda-idl2ada                     === --
-- ===  Copyright Top Graph'X  1997                 === --
-- ==================================================== --
with Corba.Object ;
with Chicken_Egg_Idl_File ;
package Chicken is

   type Ref is new Corba.Object.Ref with null record;

   function To_Chicken (Self : in Corba.Object.Ref'class) return Ref'class;

   function To_Ref (From : in Corba.Any) return Ref;
   function To_Any (From : in Ref) return Corba.Any;

   function lay
      ( Self : in Ref)
         return chicken_egg_IDL_File.Egg_Forward.Ref ;

   package chicken_egg_IDL_File_Convert is new 
      chicken_egg_IDL_File.Chicken_Forward.Convert (Ref);

   Null_Ref : constant Ref := (Corba.Object.Null_Ref with null record);

   Tgx_Service_Name : Corba.ObjectId := Corba.To_Unbounded_String
      ("chicken_egg") ;

   Chicken_R_Id : constant Corba.RepositoryId :=
      Corba.To_Unbounded_String ("IDL:Chicken:1.0") ;
end Chicken;


