-- ==================================================== --
-- ===  Code automatically generated by IDL to Ada  === --
-- ===  compiler OrbAda-idl2ada                     === --
-- ===  Copyright Top Graph'X  1997                 === --
-- ==================================================== --
with Corba.Object ;
with Corba.Forward ;
package chicken_egg_IDL_File is

   package Chicken_Forward is new Corba.Forward;

   package Egg_Forward is new Corba.Forward;
end chicken_egg_IDL_File;

