-- ==================================================== --
-- ===  Code automatically generated by IDL to Ada  === --
-- ===  compiler OrbAda-idl2ada                     === --
-- ===  Copyright Top Graph'X  1997                 === --
-- ==================================================== --
with Corba.Boa ;
with Corba.Interfacedef ;
with Corba.Implementationdef ;
with Vehicle.Impl ;
package tank.Impl is
   type Object is new Vehicle.Impl.Object with private;

   type Object_Ptr is access all Object'class;

   procedure shoot
      ( Self : access Object) ;

   procedure Initialize (Oa : in Corba.Boa.Object);

   Tgx_Implementation : Corba.Implementationdef.Ref ;
   Tgx_Interface      : Corba.Interfacedef.Ref ;
   Tgx_Oa             : Corba.Boa.Object ;
private
   type Object is new Vehicle.Impl.Object with
   record
         null ;
   end record;
end tank.Impl;

