-- ==================================================== --
-- ===  Code automatically generated by IDL to Ada  === --
-- ===  compiler OrbAda-idl2ada                     === --
-- ===  Copyright Top Graph'X  1997                 === --
-- ==================================================== --
with Corba.Orb ;
with Corba_Ios ;
with Corba.Repository ;
with Corba.Interface_Repository ;
with Corba.Iop ;
package body Vehicle.Impl is
      type Tgx_Operation_Type is
       ( Tgx_Get_mark, Tgx_Set_mark, can_drive) ;

      procedure Skeleton ( Self        : in Corba.Boa.Object ;
                           Tgx_Object  : in Corba.Boa.Object_Impl_Access ;
                           Tgx_Request : in Corba.Iop.Request_Header ;
                           Tgx_Stream  : access Corba_Ios.Iop_Stream_Type ) ;

      procedure Initialize (Oa : in Corba.Boa.Object) is
         Ir      : Corba.Repository.Ref ;
         The_Orb : Corba.Orb.Object := Corba.Boa.Orb_Id (Oa) ;
      begin
         Tgx_Oa := Oa ;
         Corba.Object.Ref (Ir) := Corba.Orb.Resolve_Initial_References
            (The_Orb, Corba.Interface_Repository.Tgx_Service_Name) ;
         Corba.Object.Ref (Tgx_Interface) := Corba.Object.Ref
            (Corba.Repository.Lookup_Id (Ir, Vehicle_R_Id)) ;
         Tgx_Implementation := Corba.Boa.Create
            ( Self        => Oa,
              Name        => Tgx_Service_Name,
              Interface   => Tgx_Interface,
              Activation  => Corba.Shared_Server,
              Impl_Server => Corba.Boa.Service_Path_Name,
              Type_Id     => Vehicle_R_Id,
              D_I_R       => null,
              Skeleton    => Skeleton'access) ;

         Corba.Boa.Impl_Is_Ready (Self => Oa, Impl => Tgx_Implementation) ;
      end Initialize ;

      procedure Skeleton ( Self        : in Corba.Boa.Object ;
                           Tgx_Object  : in Corba.Boa.Object_Impl_Access ;
                           Tgx_Request : in Corba.Iop.Request_Header ;
                           Tgx_Stream  : access Corba_Ios.Iop_Stream_Type ) is
         Tgx_Op_Name   : constant Standard.String := Corba.Iop.To_String
            (Tgx_Request.Operation) ;
         Tgx_Operation : Tgx_Operation_Type ;
         Tgx_Obj       : Object_Ptr ;
         Tgx_Orb       : Corba.Orb.Object := Corba.Boa.Orb_Id (Self) ;
         pragma Suppress (Range_Check) ;
      begin
         Tgx_Obj := Object_Ptr (Tgx_Object) ;
         if Tgx_Op_Name (Tgx_Op_Name'first) = '_'
         then
            Tgx_Operation := Tgx_Operation_Type'value ("Tgx" & Tgx_Op_Name) ;
         else
            Tgx_Operation := Tgx_Operation_Type'value (Tgx_Op_Name) ;
         end if ;
         case Tgx_Operation is
         when Tgx_Get_mark =>
            -- Declare required temporary variables
            declare
               Tgx_Result : Corba.String ;
            begin
               -- Call attribute
               Tgx_Result := mark_Of (Self => Tgx_Obj) ;
               -- Build reply
               Corba.Orb.Write_Reply
                  ( Stream    => Tgx_Stream,
                    Id        => Tgx_Request.Id,
                    Status    => Corba.Iop.No_Exception) ;

               -- Put the result
               Corba.String'Write (Tgx_Stream, Tgx_Result) ;

               -- Send message to the client via the ORB
               Corba.Orb.Service_Send ( Self   => Tgx_Orb,
                                        Stream => Tgx_Stream ) ;
            end ;
         when Tgx_Set_mark =>
            -- Declare required temporary variables
            declare
               Tgx_Result : Corba.String ;
            begin
               -- Get attribute
               Corba.String'Read (Tgx_Stream, Tgx_Result) ;

               -- Call attribute
               Set_mark
                  (Self => Tgx_Obj, To => Tgx_Result) ;

               if not Tgx_Request.Response_Expected
               then
                  return ;
               end if ;

               -- Build reply
               Corba.Orb.Write_Reply
                  ( Stream    => Tgx_Stream,
                    Id        => Tgx_Request.Id,
                    Status    => Corba.Iop.No_Exception) ;

               -- Send message to the client via the ORB
               Corba.Orb.Service_Send ( Self   => Tgx_Orb,
                                        Stream => Tgx_Stream ) ;
            end ;

         when can_drive =>
            -- Declare required temporary variables
            declare
               age : Corba.Unsigned_Short;
               Tgx_Result : Corba.Boolean ;
            begin
               -- Get params
               Corba.Unsigned_Short'Read (Tgx_Stream, age);

               -- Call operation
               Tgx_Result := can_drive
                  ( Self => Tgx_Obj,
                    age => age) ;

               -- Check if the client needs the result
               if not Tgx_Request.Response_Expected
               then
                  return ;
               end if ;
               -- Build the reply
               Corba.Orb.Write_Reply
                  ( Stream    => Tgx_Stream,
                    Id        => Tgx_Request.Id,
                    Status    => Corba.Iop.No_Exception) ;

               -- Put the result
               Corba.Boolean'Write (Tgx_Stream, Tgx_Result) ;

               -- Write the out and inout parameters
               -- None

               -- Send message to the client via the ORB
               Corba.Boa.Service_Send ( Self   => Self,
                                        Stream => Tgx_Stream ) ;
            end ;
         end case ;

      -- Handle exceptions
      exception
      when Tgx_Erroneous_Request : others =>
         Corba.Boa.Send_Exception_Reply ( Self => Self,
                                          Id   => Tgx_Request.Id,
                                          X    => Tgx_Erroneous_Request) ;
      end Skeleton ;

   function mark_Of
      (Self : access Object) return Corba.String is separate ;
   --[Separate body is to be filled by the service implementor]

   procedure Set_mark
      (Self : access Object;
       To : in Corba.String) is separate ;
   --[Separate body is to be filled by the service implementor]

   function can_drive
      ( Self : access Object;
        age : in Corba.Unsigned_Short)
         return Corba.Boolean is separate ;
   --[Separate body is to be filled by the service implementor]
end Vehicle.Impl;

