-- ==================================================== --
-- ===  Code automatically generated by IDL to Ada  === --
-- ===  compiler OrbAda-idl2ada                     === --
-- ===  Copyright Top Graph'X  1997                 === --
-- ==================================================== --
with Corba.Object ;
package Weapon is

   type Ref is new Corba.Object.Ref with null record;

   function To_Weapon (Self : in Corba.Object.Ref'class) return Ref'class;

   function To_Ref (From : in Corba.Any) return Ref;
   function To_Any (From : in Ref) return Corba.Any;

   type name is new Corba.String;

   procedure shoot
      ( Self : in Ref) ;

   Null_Ref : constant Ref := (Corba.Object.Null_Ref with null record);

   Tgx_Service_Name : Corba.ObjectId := Corba.To_Unbounded_String
      ("weapon") ;

   Weapon_R_Id : constant Corba.RepositoryId :=
      Corba.To_Unbounded_String ("IDL:Weapon:1.0") ;
end Weapon;


