-- ==================================================== --
-- ===  Code automatically generated by IDL to Ada  === --
-- ===  compiler OrbAda-idl2ada                     === --
-- ===  Copyright Top Graph'X  1997                 === --
-- ==================================================== --
with Corba.Type_Codes;
pragma Elaborate (Corba.Type_Codes);
package Weapon.Typecodes is
   Tc_name : constant Corba.Typecode.Object :=
      Corba.Type_Codes.Convert_to_Tc
         (( 0, 0, 0, 21, 0, 0, 0, 44, 0, 0, 0, 20, 73, 68, 76, 58, 87, 101,
            97, 112, 111, 110, 47, 110, 97, 109, 101, 58, 49, 46, 48, 0, 0,
            0, 0, 5, 110, 97, 109, 101, 0, 0, 0, 0, 0, 0, 0, 18, 0, 0, 0, 0));
end Weapon.Typecodes;

