-- ==================================================== --
-- ===  Code automatically generated by IDL to Ada  === --
-- ===  compiler OrbAda-idl2ada                     === --
-- ===  Copyright Top Graph'X  1997                 === --
-- ==================================================== --
with Corba.Boa ;
with Corba.Interfacedef ;
with Corba.Implementationdef ;
package Weapon.Impl is
   type Object is new Corba.Boa.Object_Impl with private;
   type Object_Ptr is access all Object'class;

   procedure Initialize (Oa : in Corba.Boa.Object);

   procedure shoot
      ( Self : access Object) ;

   Tgx_Implementation : Corba.Implementationdef.Ref ;
   Tgx_Interface      : Corba.Interfacedef.Ref ;
   Tgx_Oa             : Corba.Boa.Object ;
private
   type Object is new Corba.Boa.Object_Impl with
   record
         null ;
   end record;
end Weapon.Impl;

