module m {
  interface int1 {
     short op1();
     attribute long attr1, attr11;
  };
  interface int2 {
     short op2();
     attribute long attr2, attr22;
  };
  interface int3 : int1, int2 {
     short op3();
     attribute long attr3, attr33;
  };
};

