#! /bin/sh

# Usage: kill-process <pid>
# Kills the process whose process id is <pid>.

# This is needed to deal with differences between Unix and Windows.
# On Windows, $OS is defined as below; on Unix it is not defined.
# tskill is part of the Windows system, normally found in something
# like /c/WINDOWS/system32/tskill.

if [ "$OS" = "Windows_NT" ]; then
  # On windows tskill is present from Windows 2000 to Windows 2008 included.
  # Starting with Windows 7 only taskkill is present (appeared with Windows
  # Vista).
  if [ -f /cygdrive/c/windows/system32/tskill.exe ]; then
     tskill $*
  else
     for p in $*; do
        taskkill /F /PID $p >/dev/null
     done
  fi
else
  kill -9 $*
fi
