#!/bin/sh
#
# Compute build dependencies
# $Id$
#

unset LANG LC_ALL LC_COLLATE
PREFIXLIST=

while true
do
  case "$1" in
    -I*)
      PREFIXLIST="${PREFIXLIST}"`echo "$1" | sed 's/^-I//'`:
      shift
      ;;
    -*)
      shift
      ;;
    *)
      break
      ;;
  esac
done

PREFIX=$1

FNAME=${PREFIX}/Makefile.am
MKDEP="### DO NOT REMOVE THIS LINE, IT IS USED BY MAKEDEPEND ###"
rm -f $FNAME.bak
cp $FNAME $FNAME.bak
(sed -e "/$MKDEP/,\$d" < $FNAME.bak
echo $MKDEP
for k in *.ali; do
  i=`echo $k | sed -e 's/\.ali$//'`
  withlist=
  for j in `sed -n -e '/^D /p' $k | awk '{print $2}'`; do
    if [ -f ${PREFIX}/$j ]; then
      withlist="$withlist $j"
    else
      saveIFS="${IFS}"
      IFS=": "
      for p in `echo ${PREFIXLIST}`
      do
        if [ -f ${p}/${j} ]; then
          withlist="$withlist ${p}/${j}"
        fi
      done
      IFS="${saveIFS}"
    fi
  done
  if [ "x$withlist" != x ]; then
    echo "${i}.lo:`echo $withlist | tr ' ' '\n' | sort | tr '\n' ' '`"
  fi
done
) > $FNAME
