# -*- makefile -*-
#
# $Id$
#
# Makefile portion for the ZIP filter.
#

zip-objects = \
s-gafizi.o

zip-sources = \
${srcdir}/s-gafizi.ads ${srcdir}/s-gafizi.adb

zip-extra-objects = adler32.o compress.o crc32.o gzio.o \
	uncompr.o deflate.o trees.o zutil.o \
	inflate.o infblock.o inftrees.o \
	infcodes.o infutil.o inffast.o

%.o: $(srcdir)/zlib/%.c
	$(CC) -c -O2 -I$(srcdir)/zlib $<

libz.a: $(zip-extra-objects)
	$(AR) cq libz.a $(zipLIBOBJS)

install-zlib: libz.a
	$(INSTALL_DATA) libz.a $(GARLIC)
	$(RANLIB) $(GARLIC)/libz.a

# Dependency

Makefile.fil Makefile.in: Makefile.zip
