#
# $Id$
#
# Makefile portion for the ZIP filter.
#

ZIPOBJECTS = \
s-gafizi.o

ZIPSOURCES = \
${srcdir}/s-gafizi.ads ${srcdir}/s-gafizi.adb

ZIPLIBOBJS = adler32.o compress.o crc32.o gzio.o \
	uncompr.o deflate.o trees.o zutil.o \
	inflate.o infblock.o inftrees.o \
	infcodes.o infutil.o inffast.o

%.o: $(srcdir)/zlib/%.c
	$(CC) -c -O2 -I$(srcdir)/zlib $<

FILTERSOBJECTS += $(ZIPOBJECTS) $(ZIPLIBOBJS)
FILTERSSOURCES += $(ZIPSOURCES)

# Dependency

Makefile.fil: Makefile.zip
