// IDL-Spec for testgroup: valuetype
// Purpose:  Valuetype as member in an exception,


valuetype Val {
  public short ShortMbr;
  exception ValExcpt {
	Val ex1;
  };
  Val op1() 
	raises(ValExcpt);
};


interface Inf {
  exception ValExcpt {
	Val ex1;
  };
  Val op2()
	raises(ValExcpt);
};
