// File: CORBA_Stream.idl
// CORBA 3.0, Chapter 5

    typedef sequence<any>                AnySeq;
    typedef sequence<boolean>            BooleanSeq;
    typedef sequence<char>               CharSeq;
    typedef sequence<wchar>              WCharSeq;
    typedef sequence<octet>              OctetSeq;
    typedef sequence<short>              ShortSeq;
    typedef sequence<unsigned short>     UShortSeq;
    typedef sequence<long>               LongSeq;
    typedef sequence<unsigned long>      ULongSeq;
    typedef sequence<long long>          LongLongSeq;
    typedef sequence<unsigned long long> ULongLongSeq;
    typedef sequence<float>              FloatSeq;
    typedef sequence<double>             DoubleSeq;
    typedef sequence<long double>        LongDoubleSeq;
    typedef sequence<string>             StringSeq;
    typedef sequence<wstring>            WStringSeq;

//PolyORB:NI:    exception BadFixedValue {
//PolyORB:NI:        unsigned long offset;
//PolyORB:NI:    };
//PolyORB:NI:
//PolyORB:NI:    abstract valuetype DataOutputStream {
//PolyORB:NI:        void write_any              (in any                 value);
//PolyORB:NI:        void write_boolean          (in boolean             value);
//PolyORB:NI:        void write_char             (in char                value);
//PolyORB:NI:        void write_wchar            (in wchar               value);
//PolyORB:NI:        void write_octet            (in octet               value);
//PolyORB:NI:        void write_short            (in short               value);
//PolyORB:NI:        void write_ushort           (in unsigned short      value);
//PolyORB:NI:        void write_long             (in long                value);
//PolyORB:NI:        void write_ulong            (in unsigned long       value);
//PolyORB:NI:        void write_longlong         (in long long           value);
//PolyORB:NI:        void write_ulonglong        (in unsigned long long  value);
//PolyORB:NI:        void write_float            (in float               value);
//PolyORB:NI:        void write_double           (in double              value);
//PolyORB:NI:        void write_longdouble       (in long double         value);
//PolyORB:NI:        void write_string           (in string              value);
//PolyORB:NI:        void write_wstring          (in wstring             value);
//PolyORB:NI:        void write_Object           (in Object              value);
//PolyORB:NI:        void write_Abstract         (in AbstractBase        value);
//PolyORB:NI:        void write_Value            (in ValueBase           value);
//PolyORB:NI:        void write_TypeCode         (in TypeCode            value);
//PolyORB:NI:        void write_any_array        (in AnySeq              seq,
//PolyORB:NI:                                     in unsigned long       offset,
//PolyORB:NI:                                     in unsigned long       length);
//PolyORB:NI:        void write_boolean_array    (in BooleanSeq          seq,
//PolyORB:NI:                                     in unsigned long       offset,
//PolyORB:NI:                                     in unsigned long       length);
//PolyORB:NI:        void write_char_array       (in CharSeq             seq,
//PolyORB:NI:                                     in unsigned long       offset,
//PolyORB:NI:                                     in unsigned long       length);
//PolyORB:NI:        void write_wchar_array      (in WCharSeq            seq,
//PolyORB:NI:                                     in unsigned long       offset,
//PolyORB:NI:                                     in unsigned long       length);
//PolyORB:NI:        void write_octet_array      (in OctetSeq            seq,
//PolyORB:NI:                                     in unsigned long       offset,
//PolyORB:NI:                                     in unsigned long       length);
//PolyORB:NI:        void write_short_array      (in ShortSeq            seq,
//PolyORB:NI:                                     in unsigned long       offset,
//PolyORB:NI:                                     in unsigned long       length);
//PolyORB:NI:        void write_ushort_array     (in UShortSeq           seq,
//PolyORB:NI:                                     in unsigned long       offset,
//PolyORB:NI:                                     in unsigned long       length);
//PolyORB:NI:        void write_long_array       (in LongSeq             seq,
//PolyORB:NI:                                     in unsigned long       offset,
//PolyORB:NI:                                     in unsigned long       length);
//PolyORB:NI:        void write_ulong_array      (in ULongSeq            seq,
//PolyORB:NI:                                     in unsigned long       offset,
//PolyORB:NI:                                     in unsigned long       length);
//PolyORB:NI:        void write_ulonglong_array  (in ULongLongSeq        seq,
//PolyORB:NI:                                     in unsigned long       offset,
//PolyORB:NI:                                     in unsigned long       length);
//PolyORB:NI:        void write_longlong_array   (in LongLongSeq         seq,
//PolyORB:NI:                                     in unsigned long       offset,
//PolyORB:NI:                                     in unsigned long       length);
//PolyORB:NI:        void write_float_array      (in FloatSeq            seq,
//PolyORB:NI:                                     in unsigned long       offset,
//PolyORB:NI:                                     in unsigned long       length);
//PolyORB:NI:        void write_double_array     (in DoubleSeq           seq,
//PolyORB:NI:                                     in unsigned long       offset,
//PolyORB:NI:                                     in unsigned long       length);
//PolyORB:NI:        void write_long_double_array(
//PolyORB:NI:                                     in LongDoubleSeq       seq,
//PolyORB:NI:                                     in unsigned long       offset,
//PolyORB:NI:                                     in unsigned long       length);
//PolyORB:NI:        void write_fixed            (
//PolyORB:NI:                                     in any                 fixed_value
//PolyORB:NI:                                    ) raises (BadFixedValue);
//PolyORB:NI:        void write_fixed_array      (
//PolyORB:NI:                                     in AnySeq              seq,
//PolyORB:NI:                                     in unsigned long       offset,
//PolyORB:NI:                                     in unsigned long       length
//PolyORB:NI:                                    ) raises (BadFixedValue);   
//PolyORB:NI:    };
//PolyORB:NI:
//PolyORB:NI:    abstract valuetype DataInputStream {
//PolyORB:NI:        any         read_any();
//PolyORB:NI:        boolean     read_boolean();
//PolyORB:NI:        char        read_char();
//PolyORB:NI:        wchar       read_wchar();
//PolyORB:NI:        octet       read_octet();
//PolyORB:NI:        short       read_short();
//PolyORB:NI:        unsigned    short read_ushort();
//PolyORB:NI:        long        read_long();
//PolyORB:NI:        unsigned    long read_ulong();
//PolyORB:NI:        long long   read_longlong();
//PolyORB:NI:        unsigned long long read_ulonglong();
//PolyORB:NI:        float       read_float();
//PolyORB:NI:        double      read_double();
//PolyORB:NI:        long double read_longdouble();
//PolyORB:NI:        string      read_string();
//PolyORB:NI:        wstring     read_wstring();
//PolyORB:NI:        Object      read_Object();
//PolyORB:NI:        AbstractBase read_Abstract();
//PolyORB:NI:        ValueBase   read_Value();
//PolyORB:NI:        TypeCode    read_TypeCode();
//PolyORB:NI:
//PolyORB:NI:        void read_any_array        (
//PolyORB:NI:                                    inout AnySeq        seq,
//PolyORB:NI:                                    in unsigned long    offset,
//PolyORB:NI:                                    in unsigned long    length);
//PolyORB:NI:        void read_boolean_array    (
//PolyORB:NI:                                    inout BooleanSeq    seq,
//PolyORB:NI:                                    in unsigned long    offset,
//PolyORB:NI:                                    in unsigned long    length);
//PolyORB:NI:        void read_char_array       (
//PolyORB:NI:                                    inout CharSeq       seq,
//PolyORB:NI:                                    in unsigned long    offset,
//PolyORB:NI:                                    in unsigned long    length);
//PolyORB:NI:        void read_wchar_array      (
//PolyORB:NI:                                    inout WCharSeq      seq,
//PolyORB:NI:                                    in unsigned long    offset,
//PolyORB:NI:                                    in unsigned long    length);
//PolyORB:NI:        void read_octet_array      (
//PolyORB:NI:                                    inout OctetSeq      seq,
//PolyORB:NI:                                    in unsigned long    offset,
//PolyORB:NI:                                    in unsigned long    length);
//PolyORB:NI:        void read_short_array      (
//PolyORB:NI:                                    inout ShortSeq      seq,
//PolyORB:NI:                                    in unsigned long    offset,
//PolyORB:NI:                                    in unsigned long    length);
//PolyORB:NI:        void read_ushort_array     (
//PolyORB:NI:                                    inout UShortSeq     seq,
//PolyORB:NI:                                    in unsigned long    offset,
//PolyORB:NI:                                    in unsigned long    length);
//PolyORB:NI:        void read_long_array       (
//PolyORB:NI:                                    inout LongSeq       seq,
//PolyORB:NI:                                    in unsigned long    offset,
//PolyORB:NI:                                    in unsigned long    length);
//PolyORB:NI:        void read_ulong_array      (
//PolyORB:NI:                                    inout ULongSeq      seq,
//PolyORB:NI:                                    in unsigned long    offset,
//PolyORB:NI:                                    in unsigned long    length);
//PolyORB:NI:        void read_ulonglong_array  (
//PolyORB:NI:                                    inout ULongLongSeq  seq,
//PolyORB:NI:                                    in unsigned long    offset,
//PolyORB:NI:                                    in unsigned long    length);
//PolyORB:NI:        void read_longlong_array   (
//PolyORB:NI:                                    inout LongLongSeq   seq,
//PolyORB:NI:                                    in unsigned long    offset,
//PolyORB:NI:                                    in unsigned long    length);
//PolyORB:NI:        void read_float_array      (
//PolyORB:NI:                                    inout FloatSeq      seq,
//PolyORB:NI:                                    in unsigned long    offset,
//PolyORB:NI:                                    in unsigned long    length);
//PolyORB:NI:        void read_double_array     (     
//PolyORB:NI:                                    inout DoubleSeq     seq,
//PolyORB:NI:                                    in unsigned long    offset,
//PolyORB:NI:                                    in unsigned long    length);
//PolyORB:NI:        void read_long_double_array(
//PolyORB:NI:                                    inout DoubleSeq     seq,
//PolyORB:NI:                                    in unsigned long    offset,
//PolyORB:NI:                                    in unsigned long    length);
//PolyORB:NI:        any read_fixed             (
//PolyORB:NI:                                    in unsigned short   digits,
//PolyORB:NI:                                    in short            scale
//PolyORB:NI:                                   ) raises (BadFixedValue);
//PolyORB:NI:        void read_fixed_array      (
//PolyORB:NI:                                    inout AnySeq        seq,
//PolyORB:NI:                                    in unsigned long    offset,
//PolyORB:NI:                                    in unsigned long    length,
//PolyORB:NI:                                    in unsigned short   digits,
//PolyORB:NI:                                    in short            scale
//PolyORB:NI:                                   ) raises (BadFixedValue);
//PolyORB:NI:    };
