//testsubgroup valuetype as base class
//tsgdescr "Testing  the concrete valuetype as base class"


valuetype Val1 {
//state

  public long longMbr;
  public short shtMbr;
  short op();

// initializer

  factory init(in long longMbr, in short shtMbr);
};

valuetype Val2:Val1 {
//state

  public any anyMbr;

// initializer

  factory init(in long longMbr, in short shtMbr, in any anyMbr);
};

valuetype Val3: truncatable Val1 {};
