const long x = 0x9 + 0xf;
const long y = 12 + 3 * 6 - (x / 2);
enum T {AT, BT, CT};
const string s1 = "toto";
const string s2 = L"t\uccccti";
const wstring s3 = "t\uccccti";
const wstring s4 = L"t\uccccti";
const char c1 = 'a';
const wchar c2 = L'b';
const char c3 = '\u41';
