//File: CosPersistencePDS.idl
//Part of the Persistence Service

#ifndef _COS_PERSISTENCE_PDS_IDL_
#define _COS_PERSISTENCE_PDS_IDL_
#pragma prefix "omg.org"

#include <CosPersistencePID.idl>

#pragma prefix "omg.org"

module CosPersistencePDS {

	interface PDS {
	PDS 	connect (in Object obj, 
					 in CosPersistencePID::PID p);
	void disconnect (in Object obj, 
					 in CosPersistencePID::PID p);
	void store (in Object obj, 
				in CosPersistencePID::PID p);
	void restore (in Object obj, 
				  in CosPersistencePID::PID p);
	void delete (in Object obj, 
				 in CosPersistencePID::PID p);
	};
};

#endif /* ifndef _COS_PERSISTENCE_PDS_IDL_ */
