interface time {
  attribute readonly long hours ;
  attribute readonly long minutes ;
  attribute readonly long seconds ;
}

interface Echo {

  string greetings(in string name);

  long add(in long a, in long b) ;

  // exception test
  exception there_is_a_problem {
    string why;
    int how_big;
  };
  bool is_there_a_problem() raises (there_is_a_problem) ;

  // attribute
  readonly attribute unsigned long number_of_requests ;

  // enum
  enum weather { Sunny, Cloudy, Rainy }; 
  weather today_s_weather() ;

  // sequences
  typedef sequence<short> Data ;
  Data echoData(in Data arg) ;

  // struct
  struct computer {
    string cpu ;
    string peripherials[2]
  }
  void server_type(inout computer server) ;

  // returns interface
  time get_time() ;
  
};
