//File: CosExternalizationReference.idl
//Part of the Externalization Service
// modified from version 1.0 to use CosStream module 
//     instead of CosCompoundExternalization

#ifndef _COS_EXTERNALIZATION_REFERENCE_IDL_
#define _COS_EXTERNALIZATION_REFERENCE_IDL_

#include <CosReference.idl>
#include <CosStream.idl>

#pragma prefix "omg.org"

module CosExternalizationReference {

	interface Relationship : 
		CosStream::Relationship,
		CosReference::Relationship {};

	interface ReferencesRole : 
		CosStream::Role,
		CosReference::ReferencesRole {};

	interface ReferencedByRole : 
		CosStream::Role,
		CosReference::ReferencedByRole {};
};
#endif /* ifndef _COS_EXTERNALIZATION_REFERENCE_IDL_ */
