module _module {
  module m11 {
    interface I111 {
      attribute float value; 
    };
  };
};
module m2
{
  interface I21
  {
    typedef boolean new_bool; 
    new_bool is_greater (in float f1, in float f2); 
  };
};
