//
// Copyright (c) 1997 X/Open Company Ltd., A member of The Open Group.
//
// All rights reserved. No part of this source code may be reproduced,
// stored in a retrieval system, or transmitted, in any form or by any
// means, electronic, mechanical, photocopying, recording or otherwise,
// except as stated in the end-user licence agreement, without the prior
// permission of the copyright owners.
//
// Developed for X/Open by ApTest Ireland Limited.
//
// Project: CORVAL2
//


typedef sequence<char,18>  GrannySmith;

typedef sequence<char,18>  BrazilNut[13];

typedef sequence<boolean>  SweetPotato;

typedef sequence<boolean>  Tangarine[15];

typedef sequence<boolean,11>  Billberries;

typedef sequence<boolean,7>  CantelopeMelon[10];

typedef sequence<octet>  LolloRossa;

typedef sequence<octet>  RowanBerry[19];

interface idlServer {

  exception GrannySmithExcpt{
    ::GrannySmith ex1;
  };

  attribute ::GrannySmith GrannySmithAttr;

  ::GrannySmith GrannySmithOp(
    in    ::GrannySmith p1,
    out   ::GrannySmith p2,
    inout ::GrannySmith p3
  ) raises (GrannySmithExcpt);

  exception BrazilNutExcpt{
    ::BrazilNut ex1;
  };

  attribute ::BrazilNut BrazilNutAttr;

  ::BrazilNut BrazilNutOp(
    in    ::BrazilNut p1,
    out   ::BrazilNut p2,
    inout ::BrazilNut p3
  ) raises (BrazilNutExcpt);

  exception SweetPotatoExcpt{
    ::SweetPotato ex1;
  };

  attribute ::SweetPotato SweetPotatoAttr;

  ::SweetPotato SweetPotatoOp(
    in    ::SweetPotato p1,
    out   ::SweetPotato p2,
    inout ::SweetPotato p3
  ) raises (SweetPotatoExcpt);

  exception TangarineExcpt{
    ::Tangarine ex1;
  };

  attribute ::Tangarine TangarineAttr;

  ::Tangarine TangarineOp(
    in    ::Tangarine p1,
    out   ::Tangarine p2,
    inout ::Tangarine p3
  ) raises (TangarineExcpt);

  exception BillberriesExcpt{
    ::Billberries ex1;
  };

  attribute ::Billberries BillberriesAttr;

  ::Billberries BillberriesOp(
    in    ::Billberries p1,
    out   ::Billberries p2,
    inout ::Billberries p3
  ) raises (BillberriesExcpt);

  exception CantelopeMelonExcpt{
    ::CantelopeMelon ex1;
  };

  attribute ::CantelopeMelon CantelopeMelonAttr;

  ::CantelopeMelon CantelopeMelonOp(
    in    ::CantelopeMelon p1,
    out   ::CantelopeMelon p2,
    inout ::CantelopeMelon p3
  ) raises (CantelopeMelonExcpt);

  exception LolloRossaExcpt{
    ::LolloRossa ex1;
  };

  attribute ::LolloRossa LolloRossaAttr;

  ::LolloRossa LolloRossaOp(
    in    ::LolloRossa p1,
    out   ::LolloRossa p2,
    inout ::LolloRossa p3
  ) raises (LolloRossaExcpt);

  exception RowanBerryExcpt{
    ::RowanBerry ex1;
  };

  attribute ::RowanBerry RowanBerryAttr;

  ::RowanBerry RowanBerryOp(
    in    ::RowanBerry p1,
    out   ::RowanBerry p2,
    inout ::RowanBerry p3
  ) raises (RowanBerryExcpt);
};

