interface tin {
   boolean echoBoolean(in boolean arg) ;
   short echoShort(in short arg) ;
   long echoLong(in long arg) ;
   unsigned short echoUShort(in unsigned short arg) ;
   unsigned long echoULong(in unsigned long arg) ;
   unsigned long long echoULLong(in unsigned long long arg) ;
   float echoFloat(in float arg) ;
   double echoDouble(in double arg) ;
   char echoChar(in char arg) ;
   wchar echoWChar(in wchar arg) ;
   octet echoOctet (in octet arg) ;
   string echoString (in string arg) ;
   wstring echoWString (in wstring arg) ;
   long double echolongdouble (in long double arg);
   object echoObject (in object arg);
   any echoany (in any arg);
   void echovoid (in long arg);
   long long echolonglong (in long long arg);
}; 
