module Cyclic_M {

   interface Test_Cyclic;

   interface Cyclic_I {
      struct ForwardStruct {
         Test_Cyclic F1;
      };
      ForwardStruct echoForwardStruct (in ForwardStruct arg);

      typedef short SimpleType2;
   };

   interface Test_Cyclic {
      typedef sequence <Cyclic_M::Cyclic_I::SimpleType2, 10> ShortSeq;
      ShortSeq echoShortSeq (in ShortSeq arg);
   };
   
};
