#! /bin/sh

# $Id$
# Generate a context diff of snames.ads between the GNAT and PolyORB
# branches, with normalized enumeration values.

base=//droopi/main/compilers/gnat

set -e
dir="/tmp/difsnames.$$"
mkdir $dir
trap "rm -fr $dir" 0

get_normalized() {
  p4 print -q $1 | sed 's/N + [0-9]*;/N + 999;/'
}

for f in `p4 files "$base/*.ad*" | sed 's/#.*//'`; do
  case $f in
    */snames.ads)
      eval `p4 diff2 -b polyorb_gnat -ds $f | sed -e '\
s/^.* \([^ ]*#[0-9]*\) .* \([^ ]*#[0-9]*\) .*$/f1=\1;f2=\2/
q'`
      get_normalized "$f1" > $dir/snames.ads.gnat
      get_normalized "$f2" > $dir/snames.ads
      echo "Index: $f"
      (cd $dir && diff -c snames.ads.gnat snames.ads |
        sed 's,^\([-+*][-+*][-+*]\) snames,\1 gnat/act/wave/\1,'|| true)
      ;;
    *)
      fb=`basename $f`
      p4 diff2 -b polyorb_gnat -dc $f > $dir/$fb.dif
      if grep -q "^==* < none >" $dir/$fb.dif; then
        p4 print -q $f > $dir/$fb
        (cd $dir && diff -c /dev/null $fb || true)
      else
        p4d2p < $dir/$fb.dif
      fi
      ;;
  esac
done
