//
// Copyright (c) 1997 X/Open Company Ltd., A member of The Open Group.
//
// All rights reserved. No part of this source code may be reproduced,
// stored in a retrieval system, or transmitted, in any form or by any
// means, electronic, mechanical, photocopying, recording or otherwise,
// except as stated in the end-user licence agreement, without the prior
// permission of the copyright owners.
//
// Developed for X/Open by ApTest Ireland Limited.
//
// Project: CORVAL2
//


import ::CORBA;

enum EggPlant{
  Banana,
  Carrots,
  Lemon,
  BlackCherry,
  Starfruit,
  Rhubarb
};

typedef sequence<float>  Plum[18]; 

typedef struct Zucchini{
  short Pumpkin;
} Avocado;

union Lentil switch (long) {
  case 23:
    octet Lime;
  case -25:
    Avocado Coconut;
  default :
    short Lychees;
};

interface siiServer{

  attribute float Cucumber;

  attribute double Ginger;

  attribute long Apricots;

  attribute unsigned long BlackEyedBeans;

  attribute short Leek;

  attribute unsigned short Mint;

  attribute char GardenPeas;

  attribute boolean Fig;

  attribute octet Asparagus;

  attribute string GaliaMelon;

  attribute string<23>  Sultana; 

  attribute CORBA::OObject  Turnip;

  attribute any Orange;

  attribute CORBA::TypeCode LoganBerry;

  readonly attribute float Parsnip;

  readonly attribute double Celery;

  readonly attribute long WhiteCabbage;

  readonly attribute unsigned long Aniseed;

  readonly attribute short Bayleaf;

  readonly attribute unsigned short Dill;

  readonly attribute char Oregano;

  readonly attribute boolean Beansprout;

  readonly attribute octet Almonds;

  readonly attribute string Guava;

  readonly attribute string<25>  Mushroom;

  readonly attribute CORBA::OObject  Runnerbean;

  readonly attribute any Tofu;

  readonly attribute CORBA::TypeCode Prunes;

  attribute EggPlant GrannySmith;

  attribute Plum SweetPotato;

  attribute Zucchini Billberries;

  attribute Avocado LolloRossa;

  attribute Lentil Sweetcorn;

  readonly attribute EggPlant Shallots;

  readonly attribute Plum KidneyBean;

  readonly attribute Zucchini ButterBean;

  readonly attribute Avocado GoldenDelicous;

  readonly attribute Lentil CrabApple;

  attribute long RedOnion, HazelNut, Cinnamon, GooseBerry;

  attribute EggPlant JuniperBerries, Cloves, Daikan, Mustard;
};

