// Test interface code generation  
interface Inter1 {
  attribute float Attr1;  //  Float type declaration
  attribute boolean Attr2; // boolean type declaration
  readonly attribute long Attr3; // readonly attribute
  attribute long long Attr4; 
  string Name (in short code); // operation declaration 
  void SName (in short code, in string str); 
}; 




