/***  Test of rule 2 ***/

Error
abstract Error
module mymodule {}

/***  Test of rule 3 ***/

module
module toto
module toto {};
module toto {};


/***  Test of rule 13 through 26 ***/

/* Test of rule Value2 */
custom
custom valuetype

/* Test of rule Value3 */
abstract
abstract valuetype
abstract valuetype toto

/* Test of rule Value4 */
valuetype
valuetype toto

/* Test of rule Value5 & Value6 */
valuetype toto {};
//valuetype titi supports toto

/* Test of rule Value7 */
valuetype toto;
valuetype forward_value;
valuetype forward_value;
