interface int1 {
   typedef sequence<sequence<long>> MySeq;
   MySeq echoMySeq (in MySeq data);

   struct MyStruct {
     long memb1;
     sequence<unsigned long> memb2;
     short memb3[5];
     string<3> memb4;
     wstring<12> memb5;
     fixed<12,3> fixedMember;
   };

   MyStruct echoMyStruct (in MyStruct data);

   union MyUnion switch (long) {
      case 1: long Counter;
      case 2: sequence<boolean, 5> Flag;
      case 3: sequence<sequence<char>>   Hue;
      case 5: fixed<14,6> fixedElement;
      default: long Unknown[7];
   };

   MyUnion echoMyUnion (in MyUnion data);

   typedef sequence<string> myType[3];
};
