interface all_types {

  // Simple types
  boolean echoBoolean(in boolean arg) ;
  short echoShort(in short arg) ;
  long echoLong(in long arg) ;
  unsigned short echoUShort(in unsigned short arg) ;
  unsigned long echoULong(in unsigned long arg) ;
  unsigned long long echoULLong(in unsigned long long arg) ;
  float echoFloat(in float arg) ;
  double echoDouble(in double arg) ;
  char echoChar(in char arg) ;
  octet echoOctet (in octet arg) ;

  // Simple types, method with multiple parameters
  long echoBooleanAndLong (in boolean arg1, in long arg2);
  short echoBooleanAndShort (in boolean arg1, in short arg2);

  typedef sequence <short, 10> B_sequence;
  B_sequence echoBsequence (in B_sequence arg);
 

  union simple_union switch (long) {
  case 1 : float    Counter;
  case 2 : boolean  Flag;
  case 3 : long     Val;
  default: boolean  Unknown;
  };
  simple_union echoUnion (in simple_union arg) ;

  string echoString (in string arg);

  typedef sequence<short> U_sequence;
  U_sequence echoUsequence (in U_sequence arg);

  //  Multiple unbounded type parameters
  simple_union echoUnionAndString (in simple_union arg1, in string arg2) ;
  string echoStringAndUnion (in simple_union arg1, in string arg2) ;

  //  simple struct
  struct simple_struct {
    long a;
    float b;
    char c;
  };
  
  simple_struct echoStruct (in simple_struct arg);
  
  // struct with unbounded atrributes type

  struct complex_struct {
    simple_union a;
    string b;
    long c;
  };
    
  void StopServer ();
  // Shut down server
};
