//File: CosTradingDynamic.idl
//Part of the Trading Object Service
//OMG File: 98-10-49

#ifndef _COS_TRADING_DYNAMIC_IDL_
#define _COS_TRADING_DYNAMIC_IDL_

#ifdef _PRE_3_0_COMPILER_
#include <orb.idl>
#include <CosTrading.idl>
#pragma prefix "omg.org"
#else
import ::CORBA;
import ::CosTrading;
#endif // _PRE_3_0_COMPILER_

module CosTradingDynamic {

#ifndef _PRE_3_0_COMPILER_
	typeprefix CosTradingDynamic "omg.org";
#endif // _PRE_3_0_COMPILER_

	exception DPEvalFailure {
		CosTrading::PropertyName name;
		CORBA::TypeCode returned_type;
		any extra_info;
	};

	interface DynamicPropEval {

		any evalDP (
			in CosTrading::PropertyName name,
			in CORBA::TypeCode returned_type,
			in any extra_info
		) raises (
			DPEvalFailure
		);
	};

	struct DynamicProp {
		 DynamicPropEval eval_if;
		 CORBA::TypeCode returned_type;
		 any extra_info;
	};
}; /* end module CosTradingDynamic */

#endif /* ifndef _COS_TRADING_DYNAMIC_IDL_ */

