//File: CosLifeCycleContainment.idl
//Part of the Lifecycle Service
//OMG File: 98-10-16

#ifndef _COS_LIFE_CYCLE_CONTAINMENT_IDL_
#define _COS_LIFE_CYCLE_CONTAINMENT_IDL_

#ifdef _PRE_3_0_COMPILER_ 
#include <CosContainment.idl>
#include <CosCompoundLifeCycle.idl>
#pragma prefix "omg.org"
#else
import ::CosContainment;
import ::CosCompoundLifeCycle;
#endif // _PRE_3_0_COMPILER_

module CosLifeCycleContainment {

#ifndef _PRE_3_0_COMPILER_
	typeprefix CosLifeCycleContainment "omg.org";
#endif // _PRE_3_0_COMPILER_

	interface Relationship : 
			CosCompoundLifeCycle::Relationship,
			CosContainment::Relationship {};

	interface ContainsRole : 
			CosCompoundLifeCycle::Role,
			CosContainment::ContainsRole {};

	interface ContainedInRole : 
			CosCompoundLifeCycle::Role,
			CosContainment::ContainedInRole {};
};
#endif /* ifndef _COS_LIFE_CYCLE_CONTAINMENT_IDL_ */
