
import ::PortableInterceptor;

//module Test001_Idl {
//
interface Test001_Interface {
    exception Test_Exception {};

//        void Proc ()
//            raises (Test_Exception);

    long Func (in long Value)
        raises (Test_Exception);
};

local interface Test001_Client_Interceptor :
    PortableInterceptor::ClientRequestInterceptor {};

local interface Test001_Server_Interceptor :
    PortableInterceptor::ServerRequestInterceptor {};

local interface Test001_ORB_Initializer :
    PortableInterceptor::ORBInitializer {};

//};
