//
// Copyright (c) 1997 X/Open Company Ltd., A member of The Open Group.
//
// All rights reserved. No part of this source code may be reproduced,
// stored in a retrieval system, or transmitted, in any form or by any
// means, electronic, mechanical, photocopying, recording or otherwise,
// except as stated in the end-user licence agreement, without the prior
// permission of the copyright owners.
//
// Developed for X/Open by ApTest Ireland Limited.
//
// Project: CORVAL2
//


typedef sequence<sequence<short,18> ,18>  Melon;

typedef sequence<sequence<unsigned long> >  Elderberry[13];

typedef sequence<sequence<unsigned long,15> >  Fennell;

typedef sequence<sequence<unsigned long,11> ,7>  Chickpea[10];

typedef sequence<sequence<unsigned short> ,19>  Plantain;

typedef sequence<sequence<unsigned short,12> >  LimaBean[6];

typedef sequence<sequence<char> >  RedPepper;

typedef sequence<sequence<char> ,9>  Sharanfruit[7];

interface idlServer {

  exception MelonExcpt{
    ::Melon ex1;
  };

  attribute ::Melon MelonAttr;

  ::Melon MelonOp(
    in    ::Melon p1,
    out   ::Melon p2,
    inout ::Melon p3
  ) raises (MelonExcpt);

  exception ElderberryExcpt{
    ::Elderberry ex1;
  };

  attribute ::Elderberry ElderberryAttr;

  ::Elderberry ElderberryOp(
    in    ::Elderberry p1,
    out   ::Elderberry p2,
    inout ::Elderberry p3
  ) raises (ElderberryExcpt);

  exception FennellExcpt{
    ::Fennell ex1;
  };

  attribute ::Fennell FennellAttr;

  ::Fennell FennellOp(
    in    ::Fennell p1,
    out   ::Fennell p2,
    inout ::Fennell p3
  ) raises (FennellExcpt);

  exception ChickpeaExcpt{
    ::Chickpea ex1;
  };

  attribute ::Chickpea ChickpeaAttr;

  ::Chickpea ChickpeaOp(
    in    ::Chickpea p1,
    out   ::Chickpea p2,
    inout ::Chickpea p3
  ) raises (ChickpeaExcpt);

  exception PlantainExcpt{
    ::Plantain ex1;
  };

  attribute ::Plantain PlantainAttr;

  ::Plantain PlantainOp(
    in    ::Plantain p1,
    out   ::Plantain p2,
    inout ::Plantain p3
  ) raises (PlantainExcpt);

  exception LimaBeanExcpt{
    ::LimaBean ex1;
  };

  attribute ::LimaBean LimaBeanAttr;

  ::LimaBean LimaBeanOp(
    in    ::LimaBean p1,
    out   ::LimaBean p2,
    inout ::LimaBean p3
  ) raises (LimaBeanExcpt);

  exception RedPepperExcpt{
    ::RedPepper ex1;
  };

  attribute ::RedPepper RedPepperAttr;

  ::RedPepper RedPepperOp(
    in    ::RedPepper p1,
    out   ::RedPepper p2,
    inout ::RedPepper p3
  ) raises (RedPepperExcpt);

  exception SharanfruitExcpt{
    ::Sharanfruit ex1;
  };

  attribute ::Sharanfruit SharanfruitAttr;

  ::Sharanfruit SharanfruitOp(
    in    ::Sharanfruit p1,
    out   ::Sharanfruit p2,
    inout ::Sharanfruit p3
  ) raises (SharanfruitExcpt);
};

