//File: DCE_CIOPSecurity.idl
//Part of the Security Service

#ifndef _DCE_CIOP_SECURITY_IDL
#define _DCE_CIOP_SECURITY_IDL

#include <IOP.idl>

#pragma prefix "omg.org"

module DCE_CIOPSecurity {
	const IOP::ComponentId	TAG_DCE_SEC_MECH = 103;
	typedef unsigned short	DCEAuthorization; 
	const DCEAuthorization	DCEAuthorizationNone = 0;
	const DCEAuthorization	DCEAuthorizationName = 1;
	const DCEAuthorization	DCEAuthorizationDCE = 2;

	struct DCESecurityMechanismInfo {
		DCEAuthorization	          authorization_service;
		sequence <IOP::TaggedComponent>   components;
	};
};
#endif /* _DCE_CIOP_SECURITY_IDL */
