//File: CosObjectIdentity.idl
//Part of the Relationship Service

#ifndef _COS_OBJECT_IDENTITY_IDL_
#define _COS_OBJECT_IDENTITY_IDL_
#pragma prefix "omg.org"

module CosObjectIdentity {

	typedef unsigned long ObjectIdentifier;

	interface IdentifiableObject {
		readonly attribute ObjectIdentifier constant_random_id;
		boolean is_identical (
			in IdentifiableObject other_object);
	};

};
        
#endif /* ifndef _COS_OBJECT_IDENTITY_IDL_ */
