// IDL-Spec for testgroup: valuetype
// Purpose:  Valuetype as operation parameter and attribute in a valuetype,
// valuetype as operation parameter and attribute in an interface

valuetype Val {
  public short ShortMbr;
  attribute Val ValAttr;
  Val op1(in Val inPara, inout Val ioPara, out Val outPara);
};


interface Inf {
  attribute Val ValAttr;
  Val op2(in Val inPara, inout Val ioPara, out Val outPara);
};
