IDLAC = ../../idlac/idlac

EXAMPLES_GNATMAKE_FLAGS = -I$(srcdir)/../generic \
                          -I../../src \
                          -I$(srcdir)/../../src \
                          -I../../adasockets/src \
                          -I$(srcdir)/../../adasockets/src \
                          -g -O2

CLEANFILES = *.o *.ali b~*.*

%.ads %.adb: %.idl
	$(IDLAC) $<

force::
