#ADB =???  
EXE= $(patsubst %.adb,%, $(ADB))
ORK_EXE= $(patsubst %.adb,%.ork, $(ADB))

#srcdir= path/to/polyorb/src
#ork_srcdir= path/to/polyorb_compiled_for_ORK/src

#	Need to precise the PolyORB src directory path (put it in srcdir) 
#	ork_srcdir is used if you want to compile for ORK, compile PolyORB
#	for ORK platforms and initialize this variable with the src 
#	directory of PolyORB compiled for ORK





GNATFLAGS = -g -O2 -gnatfy -gnatoa -fstack-check -gnatwae #-a

GNATMAKE = gnatmake
ORK_GNATMAKE = i386-ork-gnatmake

INCLUDE =  -I../protocol -I$(srcdir) 

ORK_INCLUDE = -I. -I../ -I../../protocol -I../../../ork/ork_common/ \
-I$(ork_srcdir)


LARGS=
ORK_LARGS = -largs -k -specs ork_specs 

CMD = ${GNATMAKE} ${GNATFLAGS} ${INCLUDE}


all: #compile ork_compile
	@-echo "make compile     : Compile for Linux"
	@-echo "make ork_compile : Compile for ORK"	

compile :${ADB} 
	${CMD} ${ADB} ${LARGS}

ork_compile : ${ORK_EXE} 

%.ork:%.adb
	${ORK_GNATMAKE} -o $@ $< ${GNATFLAGS} ${ORK_INCLUDE} ${ORK_LARGS} 


force:	
	
clean:
	@-rm -f *.ali *.o *~ b~* *.gz *helper* *skel* *echo.ad* GNAT*

distclean: clean
	@-rm -f $(EXE) ${ORK_EXE}
