

include Makefile.vars


################################################################3

STUB_CC=  dominanteSK.cc 

CLI = orbTools.C  client.C
SER = orbTools.C  serveur.C imageMpegLocal.C 


################################################################3

VIDEO_OBJ = VIDEO/util.o VIDEO/video.o VIDEO/parseblock.o \
	VIDEO/motionvector.o VIDEO/decoders.o \
	VIDEO/fs2.o VIDEO/fs2fast.o VIDEO/fs4.o VIDEO/hybrid.o\
	VIDEO/hybriderr.o VIDEO/2x2.o VIDEO/floatdct.o\
	VIDEO/gdith.o VIDEO/gray.o VIDEO/mono.o VIDEO/main.o\
	VIDEO/jrevdct.o VIDEO/16bit.o VIDEO/util32.o\
	VIDEO/ordered.o VIDEO/ordered2.o VIDEO/mb_ordered.o\
	VIDEO/readfile.o VIDEO/ctrlbar.o


################################################################3


all : objVideo client serveur


objVideo:
	(cd VIDEO; make)


#
#
client:$(CLI:.C=.o) $(STUB_CC:.cc=.o)
	$(CC) $(CCFLAGS) $(CLI:.C=.o) $(STUB_CC:.cc=.o) \
		$(ORB_LIB) -o client $(LIBDIRS)  $(LIBS) 

#
#
serveur:$(SER:.C=.o) objIHM $(STUB_CC:.cc=.o)
	$(CC) $(CCFLAGS) $(SER:.C=.o) $(STUB_CC:.cc=.o)  \
		$(IHM_LIB) $(ORB_LIB) -o serveur $(LIBDIRS)  $(LIBS) 

#
#

clean:
	$(RM) *.o *.cc *.hh a.out ir.out  client serveur 
	(cd VIDEO; make clean)


depend:
	$(MAKEDEP)  $(LIPS) $(SER) $(CLI) $(STUB_CC) 
	(cd VIDEO; make depend)




# C DEPENDENCIES
# DO NOT DELETE THIS LINE -- make depend depends on it.

orbTools.o: orbTools.H
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/CORBA.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/omniInternal.h
orbTools.o: /usr/include/assert.h /usr/include/stddef.h
orbTools.o: /usr/include/strings.h /usr/include/sys/feature_tests.h
orbTools.o: /usr/include/string.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/CORBA_sysdep.h
orbTools.o: /usr/local/packages/egcs/include/g++/iostream.h
orbTools.o: /usr/local/packages/egcs/include/g++/streambuf.h
orbTools.o: /usr/local/packages/egcs/include/g++/libio.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/CORBA_basetypes.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/seqtemplates.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/IOP.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/GIOP.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/IIOP.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omnithread.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omnithread/solaris.h
orbTools.o: /usr/include/thread.h /usr/include/sys/signal.h
orbTools.o: /usr/include/sys/unistd.h /usr/include/sys/time.h
orbTools.o: /usr/include/sys/types.h /usr/include/sys/isa_defs.h
orbTools.o: /usr/include/sys/machtypes.h /usr/include/sys/select.h
orbTools.o: /usr/include/time.h /usr/include/synch.h
orbTools.o: /usr/include/sys/machlock.h /usr/include/sys/synch.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/rope.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/bufferedStream.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/giopDriver.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/omniORB.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/templates.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/proxyFactory.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/Naming.hh
orbTools.o: panic.h /usr/include/stdio.h /usr/include/errno.h
orbTools.o: /usr/include/sys/errno.h /usr/include/stdlib.h bool.h
serveur.o: /usr/local/packages/egcs/include/g++/iostream.h
serveur.o: /usr/local/packages/egcs/include/g++/streambuf.h
serveur.o: /usr/local/packages/egcs/include/g++/libio.h dominante.hh
serveur.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/CORBA.h
serveur.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/omniInternal.h
serveur.o: /usr/include/assert.h /usr/include/stddef.h /usr/include/strings.h
serveur.o: /usr/include/sys/feature_tests.h /usr/include/string.h
serveur.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/CORBA_sysdep.h
serveur.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/CORBA_basetypes.h
serveur.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/seqtemplates.h
serveur.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/IOP.h
serveur.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/GIOP.h
serveur.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/IIOP.h
serveur.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omnithread.h
serveur.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omnithread/solaris.h
serveur.o: /usr/include/thread.h /usr/include/sys/signal.h
serveur.o: /usr/include/sys/unistd.h /usr/include/sys/time.h
serveur.o: /usr/include/sys/types.h /usr/include/sys/isa_defs.h
serveur.o: /usr/include/sys/machtypes.h /usr/include/sys/select.h
serveur.o: /usr/include/time.h /usr/include/synch.h
serveur.o: /usr/include/sys/machlock.h /usr/include/sys/synch.h
serveur.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/rope.h
serveur.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/bufferedStream.h
serveur.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/giopDriver.h
serveur.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/omniORB.h
serveur.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/templates.h
serveur.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/proxyFactory.h
serveur.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/Naming.hh
serveur.o: imageMpegLocal.H /usr/include/stdio.h /usr/include/stdlib.h
serveur.o: /usr/local/packages/egcs/include/g++/iomanip.h /usr/include/math.h
serveur.o: /usr/include/signal.h /usr/include/netinet/in.h
serveur.o: /usr/include/sys/stream.h /usr/include/sys/vnode.h
serveur.o: /usr/include/sys/t_lock.h /usr/include/sys/dki_lkinfo.h
serveur.o: /usr/include/sys/dl.h /usr/include/sys/sleepq.h
serveur.o: /usr/include/sys/turnstile.h /usr/include/sys/param.h
serveur.o: /usr/include/sys/pirec.h /usr/include/sys/mutex.h
serveur.o: /usr/include/sys/rwlock.h /usr/include/sys/semaphore.h
serveur.o: /usr/include/sys/condvar.h /usr/include/sys/cred.h
serveur.o: /usr/include/sys/uio.h /usr/include/vm/seg_enum.h
serveur.o: /usr/include/sys/poll.h /usr/include/sys/strmdep.h
serveur.o: /usr/include/sys/byteorder.h varBuffer.H protectedShMem.H panic.h
serveur.o: /usr/include/errno.h /usr/include/sys/errno.h bool.h
serveur.o: protectedShMem.C /usr/include/unistd.h /usr/include/sys/ipc.h
serveur.o: /usr/include/sys/shm.h varBuffer.C VIDEO/video.h
serveur.o: /usr/X11R6/include/X11/Xlib.h /usr/X11R6/include/X11/X.h
serveur.o: /usr/X11R6/include/X11/Xfuncproto.h
serveur.o: /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xutil.h
serveur.o: VIDEO/util.h VIDEO/dither.h VIDEO/ctrlbar.h VIDEO/decoders.h
serveur.o: VIDEO/util.h VIDEO/fs2.h VIDEO/fs4.h orbTools.H
orbTools.o: orbTools.H
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/CORBA.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/omniInternal.h
orbTools.o: /usr/include/assert.h /usr/include/stddef.h
orbTools.o: /usr/include/strings.h /usr/include/sys/feature_tests.h
orbTools.o: /usr/include/string.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/CORBA_sysdep.h
orbTools.o: /usr/local/packages/egcs/include/g++/iostream.h
orbTools.o: /usr/local/packages/egcs/include/g++/streambuf.h
orbTools.o: /usr/local/packages/egcs/include/g++/libio.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/CORBA_basetypes.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/seqtemplates.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/IOP.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/GIOP.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/IIOP.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omnithread.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omnithread/solaris.h
orbTools.o: /usr/include/thread.h /usr/include/sys/signal.h
orbTools.o: /usr/include/sys/unistd.h /usr/include/sys/time.h
orbTools.o: /usr/include/sys/types.h /usr/include/sys/isa_defs.h
orbTools.o: /usr/include/sys/machtypes.h /usr/include/sys/select.h
orbTools.o: /usr/include/time.h /usr/include/synch.h
orbTools.o: /usr/include/sys/machlock.h /usr/include/sys/synch.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/rope.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/bufferedStream.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/giopDriver.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/omniORB.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/templates.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/proxyFactory.h
orbTools.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/Naming.hh
orbTools.o: panic.h /usr/include/stdio.h /usr/include/errno.h
orbTools.o: /usr/include/sys/errno.h /usr/include/stdlib.h bool.h
client.o: /usr/local/packages/egcs/include/g++/iostream.h
client.o: /usr/local/packages/egcs/include/g++/streambuf.h
client.o: /usr/local/packages/egcs/include/g++/libio.h /usr/include/stdio.h
client.o: /usr/include/sys/feature_tests.h dominante.hh
client.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/CORBA.h
client.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/omniInternal.h
client.o: /usr/include/assert.h /usr/include/stddef.h /usr/include/strings.h
client.o: /usr/include/string.h
client.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/CORBA_sysdep.h
client.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/CORBA_basetypes.h
client.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/seqtemplates.h
client.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/IOP.h
client.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/GIOP.h
client.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/IIOP.h
client.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omnithread.h
client.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omnithread/solaris.h
client.o: /usr/include/thread.h /usr/include/sys/signal.h
client.o: /usr/include/sys/unistd.h /usr/include/sys/time.h
client.o: /usr/include/sys/types.h /usr/include/sys/isa_defs.h
client.o: /usr/include/sys/machtypes.h /usr/include/sys/select.h
client.o: /usr/include/time.h /usr/include/synch.h
client.o: /usr/include/sys/machlock.h /usr/include/sys/synch.h
client.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/rope.h
client.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/bufferedStream.h
client.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/giopDriver.h
client.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/omniORB.h
client.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/templates.h
client.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/proxyFactory.h
client.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/Naming.hh
client.o: orbTools.H panic.h /usr/include/errno.h /usr/include/sys/errno.h
client.o: /usr/include/stdlib.h bool.h
dominanteSK.o: dominante.hh
dominanteSK.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/CORBA.h
dominanteSK.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/omniInternal.h
dominanteSK.o: /usr/include/assert.h /usr/include/stddef.h
dominanteSK.o: /usr/include/strings.h /usr/include/sys/feature_tests.h
dominanteSK.o: /usr/include/string.h
dominanteSK.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/CORBA_sysdep.h
dominanteSK.o: /usr/local/packages/egcs/include/g++/iostream.h
dominanteSK.o: /usr/local/packages/egcs/include/g++/streambuf.h
dominanteSK.o: /usr/local/packages/egcs/include/g++/libio.h
dominanteSK.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/CORBA_basetypes.h
dominanteSK.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/seqtemplates.h
dominanteSK.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/IOP.h
dominanteSK.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/GIOP.h
dominanteSK.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/IIOP.h
dominanteSK.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omnithread.h
dominanteSK.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omnithread/solaris.h
dominanteSK.o: /usr/include/thread.h /usr/include/sys/signal.h
dominanteSK.o: /usr/include/sys/unistd.h /usr/include/sys/time.h
dominanteSK.o: /usr/include/sys/types.h /usr/include/sys/isa_defs.h
dominanteSK.o: /usr/include/sys/machtypes.h /usr/include/sys/select.h
dominanteSK.o: /usr/include/time.h /usr/include/synch.h
dominanteSK.o: /usr/include/sys/machlock.h /usr/include/sys/synch.h
dominanteSK.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/rope.h
dominanteSK.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/bufferedStream.h
dominanteSK.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/giopDriver.h
dominanteSK.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/omniORB.h
dominanteSK.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/templates.h
dominanteSK.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/proxyFactory.h
dominanteSK.o: /infres/inf1/astre/singhoff/POLKA/COMMONv2/POLKA-ORB/include/omniORB2/Naming.hh
