//
// Copyright (c) 1997 X/Open Company Ltd., A member of The Open Group.
//
// All rights reserved. No part of this source code may be reproduced,
// stored in a retrieval system, or transmitted, in any form or by any
// means, electronic, mechanical, photocopying, recording or otherwise,
// except as stated in the end-user licence agreement, without the prior
// permission of the copyright owners.
//
// Developed for X/Open by ApTest Ireland Limited.
//
// Project: CORVAL2
//


const string Apple = "abcdefghijklmnopqrstuvwxyz";
const string Banana = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
const string Carrots = "0123456789";
const string Lemon = "!#$%&()*+,-./:;<;>@[]^ _`{|}~";
const string BlackCherry = "\n\t\v\b\r\f\a\\\?\'\"";
const string Starfruit = "\001\74\321\377";
const string PassionFruit = "\x1\xA\xe\x32\xAf\xff";

const string Orange = "abcdefghijk"
			"lmnopqrstuvwxyz";

const string Dates = "\xA" "B";

interface idlServer{

  void  Pumpkin();
};

