// XXX: Dummy empty file to provide CORBA::TypeCode interface to
// CosNotification IDL file. Actual interface and implementations are
// provided with CORBA implementation.

module CORBA {

    interface TypeCode {

    };
};
