#! /bin/sh

# This outputs elapsed = f(nmax)

# params

# nmax
# ethr
# siz

case "x$1" in
  x|xnmax) param=nmax ;;
  xethr|xsiz) param=$1 ;;
  *) echo "bad param"; exit 1 ;;
esac

tr '=' ' ' | awk '
  BEGIN { param = "'"$param"'" }
  /^nmax/ { nmax=$2 }
  /^moy/  { moy=$2 }
  /^siz/  { siz=$2 }
  /^coun/ { cnt=$2 }
  /^evolutedp_thr/ { ethr=$2 }
  /^ect/  { ect = $2;
     if (ethr == 0) ethr = 4;
     fn = sprintf ("data_%diter", cnt);
     if (param != "nmax")
       fn = (fn sprintf ("_%dcli", nmax));
     if (param != "ethr")
       fn = (fn sprintf ("_%dthr", ethr));
     if (param != "siz")
       fn = (fn sprintf ("_%dbytes", siz));
     printf "%.12g %.12g %.12g\n", '"$param"', moy, ect >> fn }'
