//------------------------------------------------------------
//
// CfmuTypes.idl
//
// IDL include file for global CFMU types
//
// Eurocontrol
//
//------------------------------------------------------------

#ifndef CFMU_TYPES_IDL
#define CFMU_TYPES_IDL

//------------------------------------------------------------
// Global definitions out of any interface.

// Following IDL guidelines, we define as few as possible typedef with string.
// Therefore, we define once CfmuStrings which will be used everywhere a list of strings objects is needed.
typedef sequence<string> CfmuStrings;

// this exception occurs when something is wrong in parameters
exception CfmuInvalid {
  string m_cause;
};

// this exception occurs when something prevent a server from doing
// its job. For example, database is missing.
exception CfmuUnavailableService {
  string m_cause;
};

// A general sequence of objects
// typedef sequence<Object> CfmuObjectList;
#endif
