// IDL-Spec for testgroup: valuetype
// Purpose: Classes for a Valuetype

valuetype Val {
  //state
  public long longMbr;
  public short shtMbr;

// initializer
  factory init(in long longMbr, in short shrMbr);
};
