//testsubgroup abstract valuetype as base class
//tsgdescr "Testing  the abstract valuetype as base class"


abstract valuetype AbsVal1 {
  short op1_1();
  long op1_2();

};

abstract valuetype AbsVal2 {
  short op2_1();
  long op2_2();

};

abstract valuetype AbsVal3: AbsVal1, AbsVal2{
  short op3();
};
