interface A {
  typedef string<128> string_t;
};
interface B {
  typedef string<256> string_t;
};
interface C: A, B {
  attribute string_t Title; // Error: string_t ambiguous
  attribute A::string_t Name; // OK
  attribute B::string_t City; // OK
};
