//File: RTPortableServer.idl
#ifndef _RT_PORTABLE_SERVER_IDL_
#define _RT_PORTABLE_SERVER_IDL_
#ifdef _PRE_3_0_COMPILER_
#pragma prefix "omg.org"

#include <PortableServer.idl>
#include <RTCORBA.idl>
#else
import ::PortableServer;
import ::RTCORBA;
#endif

// IDL
module RTPortableServer {

#ifndef _PRE_3_0_COMPILER_
    typeprefix RTCORBA "omg.org";
#endif

    local interface POA : PortableServer::POA {

	Object create_reference_with_priority (
	    in CORBA::RepositoryId intf,
	    in RTCORBA::Priority priority )
	    raises ( WrongPolicy );

	Object create_reference_with_id_and_priority (
	    in PortableServer::ObjectId oid,
	    in CORBA::RepositoryId intf,
	    in RTCORBA::Priority priority )
	    raises ( WrongPolicy );

	PortableServer::ObjectId activate_object_with_priority (
	    in PortableServer::Servant p_servant,
	    in RTCORBA::Priority priority )
	    raises ( ServantAlreadyActive, WrongPolicy );

	void activate_object_with_id_and_priority (
	    in PortableServer::ObjectId oid,
	    in PortableServer::Servant p_servant,
	    in RTCORBA::Priority priority )
	    raises ( ServantAlreadyActive, 
		     ObjectAlreadyActive, WrongPolicy );
    };

};
#endif // _RT_PORTABLE_SERVER_IDL_
