.TH IDLAC 1 "December 1, 2003" "PolyORB team" "PolyORB documentation"

.SH NAME
idlac \- PolyORB's IDL-to-Ada compiler

.SH SYNOPSIS
.B idlac [-E] [-d] [-i] [-k] [-p] [-q] [-noir] idl_file [-cppargs ...]

.SH DESCRIPTION
\fIidlac\fP is an IDL-to-Ada compiler, compliant with version 1.2 of the "Ada Language Mapping Specification" produced by the OMG.

.SH OPTIONS
.l
\fIidlac\fP accepts the following options:

.TP 8
.B  \-E
Preprocess only.
.TP 8
.B  \-d
Generate delegation package.
.TP 8
.B  \-i
Generate implementation template.
.TP 8
.B  \-k
Keep temporary files.
.TP 8
.B  \-p
Produce source on standard output.
.TP 8
.B  \-q
Be quiet.
.TP 8
.B \-noir
Don't generate code for interface repository.
.TP 8
.B \-gnatW8
Use UTF8 character encoding
.TP 8
.B \-cppargs ARGS
Pass ARGS to the C++ preprocessor.
.TP 8
.B \-I dir
Shortcut for -cppargs -I dir.

.SH AUTHORS
The \fIPolyORB\fP team, polyorb-devel@lists.act-europe.fr.

.SH SEE ALSO
.br
The \fIPolyORB\fP WWW page,
.B
http://libre.act-europe.fr/polyorb
.b
