// testsubgroup abstract valuetype as operation parameter
// tsgdescr "Testing  the abstract valuetype as operation parameter"

abstract valuetype AbsVal {
  AbsVal op1(in AbsVal inPara, inout AbsVal ioPara, out AbsVal outPara);
};
interface Itf {
  AbsVal op2(in AbsVal inPara, inout AbsVal ioPara, out AbsVal outPara);
};
