with AdaBroker;
with AdaBroker.Debug;
with AdaBroker.Constants;
with CORBA.BOA;
with CORBA.Command_Line;
with CORBA.Exceptions;
with CORBA.Forward;
with CORBA.Object;
with CORBA.ORB;
with CORBA.Sequences.Bounded;
with CORBA.Sequences.Unbounded;
with CORBA.Sequences;
with CORBA;
with AdaBroker.Exceptions;
with AdaBroker.GIOP;
with AdaBroker.GIOP_C;
with AdaBroker.GIOP_S;
with AdaBroker.IOP;
with AdaBroker.Key;
with AdaBroker.MemBufferedStream;
with AdaBroker.NetBufferedStream;
with AdaBroker.Omni;
with AdaBroker.OmniObject;
with AdaBroker.OmniOWProxyCallDesc;
with AdaBroker.OmniProxyCallDesc;
with AdaBroker.OmniProxyCallWrapper;
with AdaBroker.OmniRopeAndKey;
with AdaBroker.Rope;
with AdaBroker.Sysdep;

pragma Warnings (Off, AdaBroker);
pragma Warnings (Off, AdaBroker.Debug);
pragma Warnings (Off, AdaBroker.Constants);
pragma Warnings (Off, CORBA.BOA);
pragma Warnings (Off, CORBA.Command_Line);
pragma Warnings (Off, CORBA.Exceptions);
pragma Warnings (Off, CORBA.Forward);
pragma Warnings (Off, CORBA.Object);
pragma Warnings (Off, CORBA.ORB);
pragma Warnings (Off, CORBA.Sequences.Bounded);
pragma Warnings (Off, CORBA.Sequences.Unbounded);
pragma Warnings (Off, CORBA.Sequences);
pragma Warnings (Off, CORBA);
pragma Warnings (Off, AdaBroker.Exceptions);
pragma Warnings (Off, AdaBroker.GIOP);
pragma Warnings (Off, AdaBroker.GIOP_C);
pragma Warnings (Off, AdaBroker.GIOP_S);
pragma Warnings (Off, AdaBroker.IOP);
pragma Warnings (Off, AdaBroker.Key);
pragma Warnings (Off, AdaBroker.MemBufferedStream);
pragma Warnings (Off, AdaBroker.NetBufferedStream);
pragma Warnings (Off, AdaBroker.Omni);
pragma Warnings (Off, AdaBroker.OmniObject);
pragma Warnings (Off, AdaBroker.OmniOWProxyCallDesc);
pragma Warnings (Off, AdaBroker.OmniProxyCallDesc);
pragma Warnings (Off, AdaBroker.OmniProxyCallWrapper);
pragma Warnings (Off, AdaBroker.OmniRopeAndKey);
pragma Warnings (Off, AdaBroker.Rope);
pragma Warnings (Off, AdaBroker.Sysdep);

package Main is
end Main;
