# the following flags are system-dependant,
# they must be set to compile a program which uses omiORB
# see omniORB's user's guide chapter one for information
# All the following lines must be commented but one.

#linux
OMNIORB_SYSDEP_FLAGS = -D __x86__ -D __linux__ -D __OSVERSION__=2

#Solaris
#OMNIORB_SYSDEP_FLAGS = -D __sparc__ -D __sunos__ -D __OSVERSION__=5
