with CORBA.Policy_Values; use CORBA.Policy_Values;
with Droopi.Objects;      use Droopi.Objects;
with CORBA.POA_Types;     use CORBA.POA_Types;


package CORBA.Policy.Lifespan_Policy is

   type Lifespan_Policy is abstract new Policy with private;
   type Lifespan_Policy_Ptr is access all Lifespan_Policy;

   procedure Ensure_Oid_Lifespan
     (Self             : access Lifespan_Policy;
      OA               : access CORBA.POA_Types.Obj_Adapter;
      Oid              : Object_Id)
      is abstract;
   --  PERSISTENT:
   --  Ensure that the Oid has been generated by the current instantiation
   --  of the POA.
   --  If not, raises a BAD_PARAM exception.
   --  TRANSIENT:
   --  Does nothing.

private
   type Lifespan_Policy is abstract new Policy with
      record
         Value : LifespanPolicyValue;
      end record;


end CORBA.Policy.Lifespan_Policy;
