with CORBA.Policy_Values; use CORBA.Policy_Values;
with CORBA.POA_Types;     use CORBA.POA_Types;


package CORBA.Policy.Lifespan_Policy is

   type LifespanPolicy is abstract new Policy with
      record
         Value : LifespanPolicyValue;
      end record;
   subtype Lifespan_Policy is LifespanPolicy;
   type LifespanPolicy_Access is access all LifespanPolicy'Class;
   subtype Lifespan_Policy_Access is LifespanPolicy_Access;

   function Create (Value : LifespanPolicyValue)
                   return LifespanPolicy_Access;
   function Create (P : LifespanPolicy)
                   return LifespanPolicy_Access;
   --  The factory to create the different policies according to
   --  the value of Value

   function Create return LifespanPolicy_Access is abstract;
   --  The real creation function that has to be implemented for each
   --  possible Policy

   procedure Free (P   : in     LifespanPolicy;
                   Ptr : in out Policy_Access)
      is abstract;

--    procedure Ensure_Oid_Lifespan
--      (Self             : access LifespanPolicy;
--       OA               : access CORBA.POA_Types.Obj_Adapter;
--       Oid              : Object_Id)
--       is abstract;
--    --  PERSISTENT:
--    --  Ensure that the Oid has been generated by the current instantiation
--    --  of the POA.
--    --  If not, raises a BAD_PARAM exception.
--    --  TRANSIENT:
--    --  Does nothing.

end CORBA.Policy.Lifespan_Policy;
