--  This unit contain interface that allow build and use CORBA personality
--  without dependence from PortableInterceptors, if application don't use
--  PortableInterceptors by itself.
--
--  Note what code generated by IDL Ada translator and CORBA personality both
--  should call invocation subprograms from this package instead of direct call
--  to PolyORB neutral layer.

with PolyORB.Requests;

package PolyORB.CORBA_P.Interceptors_Hooks is

   type Client_Invoke_Handler is access procedure
     (Self  : in PolyORB.Requests.Request_Access;
      Flags : in PolyORB.Requests.Flags);

   Client_Invoke : Client_Invoke_Handler := PolyORB.Requests.Invoke'Access;

end PolyORB.CORBA_P.Interceptors_Hooks;
