interface all_types;

interface all_types {

  // simple types
  //-------------
  boolean echoBoolean(in boolean arg) ;
  short echoShort(in short arg) ;
  long echoLong(in long arg) ;
  unsigned short echoUShort(in unsigned short arg) ;
  unsigned long echoULong(in unsigned long arg) ;
  float echoFloat(in float arg) ;
  double echoDouble(in double arg) ;
  char echoChar(in char arg) ;
  octet echoOctet (in octet arg) ;
  string echoString (in string arg) ;
  all_types echoRef (in all_types arg);

  // Enum
  //-----
  enum Color { Red, Green, Blue };
  Color echoColor (in Color arg);

  // Exceptions
  //-----------
//  exception simple_exception {};
  exception my_exception {long info;};

//  void simple_exception_test () raises (simple_exception);
  void testException (in long arg) raises (my_exception);


  // Unions
  //-------
//  union example switch (long) {
//    case 1: long Counter;
//    case 2: boolean Flags;
//    default: long Unknown;
//  };

//  example echo1 (in example arg);


  // Arrays
  typedef long simple_array[5];
  simple_array echoArray (in simple_array arg);

  // Structs
  //--------
  struct simple_struct {
      long a[10];
      string s;
  };

  simple_struct echoStruct (in simple_struct arg);

//  struct manu_struct {
//    boolean a;
//    long b;
//  };

//  manu_struct inverseStruct (in manu_struct arg);



  // Strings
  //--------
//  typedef string U_string;
//  typedef string<30> B_string;

//  U_string echo4 (in U_string arg);
//  B_string echo5 (in B_string arg);


  // Sequences
  //----------
//  typedef sequence<short> U_sequence;
//  typedef sequence<long,512> B_sequence;

//  U_sequence echo6 (in U_sequence arg);
//  B_sequence echo7 (in B_sequence arg);


  // Attributes
  //-----------
//  readonly attribute Color R_attribute;
//  attribute example N_attribute;

  // Arrays
  //-------
//  typedef example line[3] ;
//  typedef simple_struct square[2][2];
//  typedef string cube[2][2][2] ;

//  line echo8 (in line arg);
//  square echo9 (in square arg);
//  cube echo10 (in cube arg);
  
  // Object
  //-------
//  all_types echo11(in all_types arg);
//  Object echo12(in Object arg);
//  all_types get_myself() ;


  // array
//  typedef long simple_array[10];
//  simple_array echoArray(in simple_array arg);

};
