'\" t
.TH adasockets-config 1 "January 8th, 2000"
.SH NAME
adasockets-config \- script to get information about the installed AdaSockets
library
.SH SYNOPSIS
.\" The general command line
.B adasockets-config 
.SH DESCRIPTION
.B adasockets-config
will echo a line on standard output such as
.I `-I/usr/lib/adasockets -L/usr/lib/adasockets'
to be used on
.B gnatmake
command line.
.SH "SEE ALSO"
.BR gnatmake (1), 
.SH AUTHORS
Samuel Tardieu <sam@inf.enst.fr>
