
typedef long b__b;
typedef long b_Ub;
typedef long b_b_;
typedef long b_b_U;
typedef string package;

module test__test{
module test{
interface test{
typedef long b__b;
typedef long b_Ub;
typedef long b_b_;
typedef long b_b_U;
};
};
};

