<!DOCTYPE HTML PUBLIC "-//W3C//DTD W3 HTML 3.2//EN">

<html>

<head>
  <title>PolyORB</title>
  <meta http-equiv="Content-Type" content="text/html">
  <meta name="description" 
        content="PolyORB generic middleware">
  <meta name="keywords" content="Thomas Quinot, Ada, Middleware, CORBA, SOAP, interoperability, GNAT">
</head>


<body bgcolor="white" background="../media/fond_globe.jpg" color="black"
      link="blue" vlink="green">

<br>
<h1><center>
<font color="#D5551E" face="lucida,helvetica" size=+4>
PolyORB Generic Middleware
</font>
</center></h1>

<br><br>
<table cellspacing=0 border=0 cellpadding=6 width="100%"><tr>
<td bgcolor="#006db6"><font face="lucida,helvetica" size=+2 color="#FFFFFF">

<b>Releases</b>
</font></td></tr></table>

<P>
<ul>
  <li>
    <a href="releases/polyorb-0.1.tar.gz">PolyORB 0.1</a> (released 2001-12-04)
    <br>
    This is the first public release of PolyORB code. This release contains
    the personality-neutral middleware core, the CORBA application personality
    (including our IDL -> Ada 95 compiler <tt>idlac</tt>), and CORBA and
    SOAP protocol personalities.
    <br>
    This should be considered as <b>test-phase</b> software.
  </li>
  <li>
    <a href="http://www.polyorb.eu.org/snapshots/">snapshots</a> of the head revision of PolyORB
    are made available from time to time. This is mainly for those interested
    in contributing to PolyORB development. Snapshots are moving targets,
    and should be considered <b>work in progress</b> software.
  </li>
</ul>

<br><br>
<table cellspacing=0 border=0 cellpadding=6 width="100%"><tr>
<td bgcolor="#006db6"><font face="lucida,helvetica" size=+2 color="#FFFFFF">
<b>Introduction to PolyORB</B>
</font></td></tr></table>

<P>

<table cellborder=0 border=0 cellpadding=4><tr><td bgcolor="#cccc99">
<font face="lucida,helvetica" size=+1 color="#000000"><B>
What is PolyORB?
</B></font></td></tr></table>

<p>
PolyORB is a polymorphic, reusable infrastructure for building object-oriented
distributed systems. Middleware environments are software libraries that
hide the complex issues of distribution and provide the programmer with
high-level abstractions that allow easy and transparent construction of
distributed applications. A number of different standards exist for
creating object-oriented distributed applications. These standards define
two things:
<ul>
<li>the interface seen by the developer's applicative objects;
<li>the protocol used by the middleware environment to talk to other
    nodes in the distributed application.
</ul>
Usually, middleware for one platform supports only one set of such
interfaces, and cannot interoperate with other platforms.

<p>
A polymorphic middleware allows the existence of several different
implementations of each of these aspects to be used within the same
middleware framework. In addition, PolyORB allows such different
personalities to coexist in the same instance of the running middleware;
it decouples the personality presented to applications on one side
("application personality"), and the personality presented to other middlewares
on the other side ("protocol personality"). Multiple implementations
of each personalisable aspect can coexist within the same instance of the
running middleware: unlike previous generic middlewares, PolyORB is
actually <em>schizophrenic</em>.

<p>
The decoupling of application and protocol personalities, and the support
for multiple simultaneous personalities within the same running middleware
are key features required for the construction of interoperable distributed
applications. This allows PolyORB to communicate with middlewares
that implement different distribution standards: PolyORB provides
<em>middleware-to-middleware</em> interoperability (M2M).

<p>
The PolyORB architecture also permits the automatic,
just-in-time creation of proxies between incompatible environments
(although this feature is not implemented yet).

<p>
<em>Note:</em> PolyORB is the project formerly known as DROOPI,
a Distributed Reusable Object-Oriented Polymorphic Infrastructure.

<p>

<table cellborder=0 border=0 cellpadding=4><tr><td bgcolor="#cccc99">
<font face="lucida,helvetica" size=+1 color="#000000"><B>
Papers related to PolyORB
</B></font></td></tr></table>

<p>
PolyORB is part of our team's research work, a joint project
between <a href="http://www.enst.fr/">ENST Paris</a> and
<a href="http://www.lip6.fr/">LIP6</a>.  Here are some of the papers
we published about PolyORB and related projects:

<p>
<? include ("publis.html"); ?>

<p>

<br><br>
<table cellspacing=0 border=0 cellpadding=6 width="100%"><tr>
<td bgcolor="#006db6"><font face="lucida,helvetica" size=+2 color="#FFFFFF">
<b>Compatibility</b>
</font></td></tr></table>

<p>

This toolkit has been developed (and tested) with

<ul>
<li><a href="http://www.gnat.com/">GNAT 3.14a1</a></li>
</ul>

Some units to develop PolyORB are GNAT-specific:

<ul>
<li><b>GNAT.Regpat</b> used in the Simple Request Protocol.</li>

<li><b>GNAT.Debug_Pools</b> used for debugging purposes (dependency
  can be removed by using the standard system storage pool instead).

<li><b>GNAT.Sockets</b> used as the interface to the system socket API.

<li><b>GNAT.HTable</b> used in several contexts where hash tables were
  desired.
</ul>

<p>
If you want to build the SOAP protocol personality, you need to
install the <a href="http://libre.act-europe.fr/XmlAda/">XmlAda</a>
library.

<p>
If you want to regenerate all generated files in PolyORB, you may also
need the following tools:
<ul>
  <li>autoconf</li>
  <li>automake</li>
  <li>Python</li>
  <li>gperf</li>
</ul>
(the files generated by these tools are included in the distribution,
so you do not need them in order to compile and install PolyORB, but
only if you make some changes to some internal PolyORB structures.)
If you do not have these tools installed, you can use the pre-generated
files included in the distribution.

<br><br>
<table cellspacing=0 border=0 cellpadding=6 width="100%"><tr>
<td bgcolor="#006db6"><font face="lucida,helvetica" size=+2 color="#FFFFFF">
<b>Related Web Sites</b>
</font></td></tr></table>

<p>

The following are some useful related web sites:

<ul>
 <li><a href="http://libre.act-europe.fr/" target=_top>Libre software for Ada</a>
     <br>
     This page provides several packages and libraries that can be used with
     the Ada language, including GtkAda, a graphical toolkit, and GVD, a
     graphical debugger.</li>
 <p>
</ul>

<br><br>
<table cellspacing=0 border=0 cellpadding=6 width="100%"><tr>
<td bgcolor="#006db6"><font face="lucida,helvetica" size=+2 color="#FFFFFF">
<b>Issues reporting</b>
</font></td></tr></table>
<p>

Please send bug reports and patches to
<a href="mailto:polyorb-bugs@polyorb.eu.org">polyorb-bugs@polyorb.eu.org</a>.

<p>

<br><br>
<table cellspacing=0 border=0 cellpadding=6 width="100%"><tr>
<td bgcolor="#006db6"><font face="lucida,helvetica" size=+2 color="#FFFFFF">
<b>Authors and contributors</b>
</font></td></tr></table>

<p>
PolyORB is primarily developed by
<a href="http://www.infres.enst.fr/~quinot/">Thomas Quinot</a> of ENST Paris.
<a href="http://www.infres.enst.fr/~pautet/">Laurent Pautet</a> (ENST Paris)
and <a href="http://www-src.lip6.fr/~Fabrice.Kordon">Fabrice Kordon</a>
also participate
in the project.

<p>
The following people have also contributed to the project:
<ul>
<li>Fabien Azavant
<li>Emmanuel Chavane
<li>Jean-Marie Cottin
<li>Michael Friess
<li>Nicolas Fritsch
<li>Mejdi Kaddour
<li>Laurent Kubler
<li>Vincent Niebel
<li>Sebastien Ponce
<li>Nicolas Setton
<li>Frank Singhoff
<li>Samuel Tardieu
</ul>

<p>
All contribution and feedback on this project are most welcome.
You can contact PolyORB developers directly or through the mailing
list
<a href="mailto:polyorb-devel@polyorb.eu.org">polyorb-devel@polyorb.eu.org</a>.

<!-- NOT YET --
--
<p>
Sorry for those we forgot, let us know and we will add you to this list.
-->

<p>
We'd like to add your name there, do not hesitate to contribute!

<hr>
<i>$Id$</i>

</body>

</html>
