module Test {
  interface Printer {
    oneway void printString (in string Mesg);
    oneway void printLong (in long K);
    string echoString (in string K);
    long echoLong (in long K);
  };

  interface Controller {
    Printer Get_Printer ();

    void StopServer ();
    // Shut down server

    boolean test_OK ();
    
  };

};
