server:
	gnatmake -I../../InterfaceORB server.adb

client:
	gnatmake -I../../InterfaceORB client.adb

echo:
	gnatmake -I../../InterfaceORB echo.adb

echoimpl:
	gnatmake -I../../InterfaceORB echo-impl.adb

