#!/bin/sh
# Pretty Print an idl file by
# 1) removing useless blanks
# 2) removing comments

BASE=`basename $0`
FILE=/tmp/$BASE.$$
if [ $# = 0 ]; then
   cat >$FILE
else
   FILE=$1
fi
sed '
/:.*arning/d
s,\t, ,g
s,//.*,,g
s,  *, ,g
s, $,,g
/^ *$/d
' $FILE
if [ $# = 0 ]; then
   rm $FILE
fi
