#!/bin/sh
DIR=`dirname $0`
PATH=$PWD:$PWD/$DIR:$PATH
if [ -d $1 ]; then
  DIR=$1;
  FILE=`ls $DIR/*.idl| awk 'BEGIN{IFS="/"}{print $NF;exit}'`
else
  DIR=`dirname $1`;
  FILE=`basename $1`
fi
TEST=`basename $DIR`
LOG=/tmp/$TEST.log
cd $DIR
if [ -f test.cmd ]; then
  sh test.cmd >$LOG 2>&1
else
  iac -idl $FILE >$LOG 2>&1
fi
if [ -f test.out ]; then
  diff test.out $LOG
else
  test ! -s $LOG
fi
CODE=$?
if [ $CODE != 0 ]; then
  echo "$DIR FAILED" | awk '{printf ("%-20s%20s\n", $1, $2)}'
  echo "--------------- expected output ------------------"
  if [ -f test.out ]; then
     cat test.out
  fi
  echo "---------------- actual output -------------------"
  cat $LOG
  echo "--------------------------------------------------"
fi;
rm $LOG 
exit $CODE
