//File: CosReference.idl
//Part of the Relationship Service

#ifndef _COS_REFERENCE_IDL_
#define _COS_REFERENCE_IDL_

#include <CosGraphs.idl>

#pragma prefix "omg.org"

module CosReference {

	interface Relationship : 
			CosRelationships::Relationship {};

	interface ReferencesRole : CosGraphs::Role {};

	interface ReferencedByRole : CosGraphs::Role {};

};
#endif /* ifndef _COS_REFERENCE_IDL_ */
