SHELL = /bin/sh
GNATCHOP = gnatchop
GNATFLAGS = -a -f -O2 -gnatpn 
GNATMAKE = gnatmake
IAC = iac
OPT_FLAGS = -hm

# FOR THE OPTIMIZATION TEST
CP=/bin/cp
SKEL=test_hash-opt.adb
ACTUAL_SKEL=test_hash-skel.adb

all: server client

force:

server: force test_hash-skel.ads 
	$(GNATMAKE) $(GNATFLAGS)  server.adb `polyorb-config`

client: force test_hash-skel.ads
	$(GNATMAKE) $(GNATFLAGS)  client.adb `polyorb-config`

test_hash-skel.ads: test_hash.idl 
	$(IAC) $(OPT_FLAGS) test_hash.idl 
	$(CP) -f $(SKEL) $(ACTUAL_SKEL)

clean: 
	@-rm -f *.o *.ali *ir_info* 
	@-rm -f client server *skel* *helper* *idl_file* 
	@-rm -f test_hash.ad* iac.ada
	@-rm -f test_hash_hash.*
	@-rm -f GNAT* 
	@-rm -f *~ 
	@-rm -f b~*

