interface test_hash {
   long echoLong00 (in long data) ;
   long echoLong01 (in long data) ;
   long echoLong02 (in long data) ;
   long echoLong03 (in long data) ;
   long echoLong04 (in long data) ;
   long echoLong05 (in long data) ;
   long echoLong06 (in long data) ;
   long echoLong07 (in long data) ;
   long echoLong08 (in long data) ;
   long echoLong09 (in long data) ;
   long echoLong10 (in long data) ;
   long echoLong11 (in long data) ;
   long echoLong12 (in long data) ;
   long echoLong13 (in long data) ;
   long echoLong14 (in long data) ;
   long echoLong15 (in long data) ;
   long echoLong16 (in long data) ;
   long echoLong17 (in long data) ;
   long echoLong18 (in long data) ;
   long echoLong19 (in long data) ;
   long echoLong20 (in long data) ;
   long echoLong21 (in long data) ;
   long echoLong22 (in long data) ;
   long echoLong23 (in long data) ;
   long echoLong24 (in long data) ;
   long echoLong25 (in long data) ;
   long echoLong26 (in long data) ;
   long echoLong27 (in long data) ;
   long echoLong28 (in long data) ;
   long echoLong29 (in long data) ;
   long echoLong30 (in long data) ;
   long echoLong31 (in long data) ;
   long echoLong32 (in long data) ;
   long echoLong33 (in long data) ;
   long echoLong34 (in long data) ;
   long echoLong35 (in long data) ;
   long echoLong36 (in long data) ;
   long echoLong37 (in long data) ;
   long echoLong38 (in long data) ;
   long echoLong39 (in long data) ;
   long echoLong40 (in long data) ;
   long echoLong41 (in long data) ;
   long echoLong42 (in long data) ;
   long echoLong43 (in long data) ;
   long echoLong44 (in long data) ;
   long echoLong45 (in long data) ;
   long echoLong46 (in long data) ;
   long echoLong47 (in long data) ;
   long echoLong48 (in long data) ;
   long echoLong49 (in long data) ;
   long echoLong50 (in long data) ;
   long echoLong51 (in long data) ;
   long echoLong52 (in long data) ;
   long echoLong53 (in long data) ;
   long echoLong54 (in long data) ;
   long echoLong55 (in long data) ;
   long echoLong56 (in long data) ;
   long echoLong57 (in long data) ;
   long echoLong58 (in long data) ;
   long echoLong59 (in long data) ;
   long echoLong60 (in long data) ;
   long echoLong61 (in long data) ;
   long echoLong62 (in long data) ;
   long echoLong63 (in long data) ;
   long echoLong64 (in long data) ;
   long echoLong65 (in long data) ;
   long echoLong66 (in long data) ;
   long echoLong67 (in long data) ;
   long echoLong68 (in long data) ;
   long echoLong69 (in long data) ;
   long echoLong70 (in long data) ;
   long echoLong71 (in long data) ;
   long echoLong72 (in long data) ;
   long echoLong73 (in long data) ;
   long echoLong74 (in long data) ;
   long echoLong75 (in long data) ;
   long echoLong76 (in long data) ;
   long echoLong77 (in long data) ;
   long echoLong78 (in long data) ;
   long echoLong79 (in long data) ;
   long echoLong80 (in long data) ;
   long echoLong81 (in long data) ;
   long echoLong82 (in long data) ;
   long echoLong83 (in long data) ;
   long echoLong84 (in long data) ;
   long echoLong85 (in long data) ;
   long echoLong86 (in long data) ;
   long echoLong87 (in long data) ;
   long echoLong88 (in long data) ;
   long echoLong89 (in long data) ;
   long echoLong90 (in long data) ;
   long echoLong91 (in long data) ;
   long echoLong92 (in long data) ;
   long echoLong93 (in long data) ;
   long echoLong94 (in long data) ;
   long echoLong95 (in long data) ;
   long echoLong96 (in long data) ;
   long echoLong97 (in long data) ;
   long echoLong98 (in long data) ;
   long echoLong99 (in long data) ;
};

