// IDL-Spec for testgroup: valuetype
// Purpose: basic features of valuetype

struct VarS {
  string strMbr;
};
valuetype VarSvalue VarS;
struct FixS {
  long longMbr;
  short shortMbr;
};
valuetype FixSvalue FixS;
