interface CORBA_InitialReferences {

  typedef string ObjId;                  // Same type as CORBA::ObjectId
  typedef sequence< string > ObjIdList;  // Same type as CORBA::ObjectIdList

  Object get(in ObjId id);
  ObjIdList list();
};

#pragma ID CORBA_InitialReferences "omg.org/CORBA/InitialReferences:1.0"
