//testsubgroup typedef_inheritance
//tsgdescr "Testing scope of typedef declarations with the valuetype inheritance"


valuetype ShortValue short;
struct FixS {
  long longMbr;
};
valuetype FixSvalue FixS;


typedef ShortValue TestType;

interface Intf {
	attribute TestType IntfAttr;
	void op1(in TestType p);
};

valuetype BaseVal {
	typedef FixSvalue TestType;
	public TestType BaseValMbr;
	void op2(in TestType p);
};

valuetype Val:BaseVal supports Intf
{
};
