// File: CORBA_CustomMarshal.idl
// CORBA 2.3, Chapter 5

 	valuetype StringValue  string;
	valuetype WStringValue wstring;

	abstract valuetype CustomMarshal {
		void marshal   (in DataOutputStream os);
		void unmarshal (in DataInputStream  is);
	};
