TOP = $(ADABROKER_TOP)/omniORB_2.7.1
CURRENT = ../$(ADABROKER_CURRENT)

ADABROKER_BOOL_DIR = $(ADABROKER_TOP)/platform/adabooltype

ADABROKER_INTERFACEORB = $(ADABROKER_TOP)/InterfaceORB

ADABROKER_FLAGS = -I$(ADABROKER_INTERFACEORB)  \
-largs -L $(ADABROKER_INTERFACEORB) -ladabroker -lstdc++

ADABROKER_LIB_DEPEND = $(ADABROKER_INTERFACEORB)/libadabroker.a

include $(TOP)/config/config.mk
