TOP = $(ADABROKER_TOP)/omniORB_2.7.0
CURRENT = ../$(ADABROKER_CURRENT)

ADABROKER_BOOLEANTYPE_DIR = $(ADABROKER_TOP)/platform/adabooltype

ADABROKER_INTERFACEORB = $(ADABROKER_TOP)/InterfaceORB

ADABROKER_FLAGS = -I$(ADABROKER_INTERFACEORB)  \
-largs -L $(ADABROKER_INTERFACEORB) -ladabroker

ADABROKER_LIB_DEPEND = $(ADABROKER_INTERFACEORB)/libadabroker.a

include $(ADABROKER_TOP)/omniORB_2.7.0/config/config.mk
