module M {
  typedef long ArgType;
  typedef ArgType AType; // line l1
  interface B {
    typedef string ArgType; // line l3
    ArgType opb(in AType i); // line l2
  };
};
module N {
  typedef char ArgType; // line l4
  interface Y : M::B {
    void opy(in ArgType i); // line l5
  };
};
