// IDL-Spec for testgroup: valuetype
// Purpose: Member of type 'any' in valuetype

interface Itf {};

struct FixStct {
  long longMbr;
};
struct VarStct {
  string stringMbr;
};

const short n=9;

union FixU switch (boolean) {
  case TRUE: long longMbr;
  case FALSE: short shortMbr;
};
union VarU switch (short) {
  case 1: string stringMbr;
  default: any anyMbr;
};

valuetype Val {
  //state
  typedef short Ar[n];
  public Ar ArMbr;
  public any anyMbr;
  public Itf ItfMbr;
  public FixStct FixStctMbr;
  public VarStct VarStctMbr;
  public FixU FixUMbr;
  public VarU VarUMbr;
};
