SHELL = /bin/sh
GNATCHOP = gnatchop
GNATFLAGS = -a -f -O2 -gnatpn
GNATMAKE = gnatmake

all: server client

force:

server: force echo-skel.ads 
	$(GNATMAKE) $(GNATFLAGS) server.adb `polyorb-config`

client: force echo-skel.ads
	$(GNATMAKE) $(GNATFLAGS) client.adb `polyorb-config`

echo-skel.ads: echo.idl 
	iac -rs echo.idl 

clean: 
	@-rm -f *.o *.ali *ir_info* 
	@-rm -f client server *skel* *helper* *cdr* *idl_file* 
	@-rm -f echo.ad* GNAT* *~
	@-rm -f b~*

