module AADL::Nodes {
  /******************/
  /* Internal types */
  /******************/

  typedef long Name_Id;

  /******************/
  /* Internal nodes */
  /******************/

  interface Node_Id {
    Node_Id    Next_Node;
    // Link nodes together
  };

  interface List_Id {
    Node_Id    First_Node;
    Node_Id    Last_Node;
  };

  

  /***********************/
  /* AADL Specifications */
  /***********************/

  // AADL_specification ::= { AADL_declaration } +

  interface AADL_Spec : List_Id {};

  // AADL_declaration ::= component_classifier | package_spec | 
  //                      port_group_type | port_group_type_extension |
  //                      system_instance | property_set

  // component_classifier ::= component_type | component_type_extension | 
  //                          component_implementation |
  //                          component_implementation_extension


  /************/
  /* Packages */
  /************/

  // package_spec ::= 
  //    package defining_package_name 
  //     ( public package_items [ private package_items ]
  //        | private package_items )
  // end defining_package_name;

  interface package_spec : Node_Id {
    Name_Id     Name;
    List_Id     Public_Items;
    List_Id     Private_Items;
  }

};
