main:
	gnatmake client -I. -I./../../generic -I../../../src -I../../../adasockets/src -L../../../adasockets/src -g -O2 -m -gnata -largs
	gnatmake server -I. -I./../../generic -I../../../src -I../../../adasockets/src -L../../../adasockets/src -g -O2 -m -gnata -largs

