#! /bin/sh

# make_tarball: construct an AdaBroker release tarball.

# $Id: //depot/adabroker/main/broca/utils/make_tarball#1 $

usage () {
  echo "Usage: $0 -C CLIENT_WORKSPACE_TOP -o OUTPUT_DIR -r RELEASE [ -c CHANGELIST ]"
  exit 1
}

while getopts C:c:o:r: opt
do
  case $opt in
    C)
      CLIENT_TOP=$OPTARG
      ;;
    c)
      CHANGELIST="@$OPTARG"
      ;;
    o)
      OUTDIR=$OPTARG
      ;;
    r)
      REL=$OPTARG
      ;;
    *)
      usage
      ;;
   esac
done

if [ "x$OUTDIR" = "x" ]
then
  usage
fi

if [ "x$CLIENT_TOP" = "x" ]
then
  usage
fi

if [ "x$REL" = "x" ]
then
  usage
fi

P4CONFIG=.p4; export P4CONFIG

set -e

cd $CLIENT_TOP
p4 sync "#none"
rm -fr $CLIENT_TOP/*
p4 sync $CHANGELIST

# CLIENT=`p4 info | awk '/^Client name:/ { print $3 }'`
CHANGE=`p4 changes -m 1 ...#have | awk '{print $2}'`
BASENAME=adabroker-$REL
TARBALL=$BASENAME-$CHANGE.tar.gz

utils/make_distrib -c DUMMY $BASENAME
mv $BASENAME.tar.gz $OUTDIR/$TARBALL
chmod 444 $OUTDIR/$TARBALL

ls -l $OUTDIR/$TARBALL

echo $CHANGE > $OUTDIR/.stamp-tarball
