#! /bin/sh

# Build AdaBroker from a distribution tarball.
# $Id: //depot/adabroker/release-1/utils/build#2 $

set -e

if [ "x$1" = x ]
then
  echo "Usage: $0 <tarball>"
  exit 1
fi

: ${GTAR:=gtar}
: ${BUILD_DIR:=`pwd`/build-`basename $1 .tar.gz`}
: ${GMAKE:=gmake}

mkdir $BUILD_DIR || true
rm -fr $BUILD_DIR/source $BUILD_DIR/install || true
mkdir $BUILD_DIR/source

$GTAR xzCf $BUILD_DIR/source $1
cd $BUILD_DIR/source
DIST_DIR=`ls`
cd $DIST_DIR
TOP=`pwd`
echo "Building AdaBroker in $TOP..."
./configure --prefix=$BUILD_DIR/install
$GMAKE
$GMAKE install

date
echo "Build finished in ${BUILD_DIR}."

