#!/bin/sh
#
# make_distrib,v 1.10 1996/05/14 07:26:34 tardieu Exp
#
# This script builds a distribution. The only parameter is the name
# of the distribution (.tar.gz will be appened). Only files tagged with
# the 'to_be_released' will be included into the release.
#
# A special case is the VERSION.INFO file, which has to be tagged
# to_be_released, but will NOT be released. In contains shell functions
# which will be sourced in order to perform the real distribution.
#

case $1 in
  -k*) kk=$1; shift;;
  *)   kk=;;
esac
tag=$1
dir=$2
root=`cat CVS/Root`
name=`sed -e "s,${root}/,," < CVS/Repository`
echo Extracting module ${name} from ${root} using tag ${tag}
prev=`pwd`
tmp=/tmp/t$$
mkdir ${tmp}
cd ${tmp}
cvs -d ${root} co ${kk} -r ${tag} -d ${dir} ${name}
cd ${dir}
if [ -f Utils/VERSION.INFO ]; then
  echo "Sourcing version file, then deleting it"
  . Utils/VERSION.INFO
  rm -f Utils/VERSION.INFO
fi
echo Doing the necessary date modifications
find . -name configure.in -exec touch {} \;
sleep 1
find . -name aclocal.m4 -exec touch {} \;
sleep 1
find . -name Makefile.in -exec touch {} \;
sleep 1
find . -name configure -exec touch {} \;
sleep 1
#echo Configuring
#./configure
#echo Building the distribution
#make
#echo Building the examples
#(cd Examples && make)
echo Adapting modes
chmod -R og=u-w .
flist=""
echo Packaging
for i in `cat MANIFEST`; do
  flist="${flist} ${dir}/${i}"
done
cd ..
tar cvf ${dir}.tar `ls -tr ${flist}`
gzip --best ${dir}.tar
mv ${dir}.tar.gz ${prev}
cd ${prev}
rm -rf ${tmp}
#pgp -sb ${dir}.tar.gz
