#! /bin/sh
# $Id$

change=`p4 changes -m 1 ... | cut -f 2 -d \ `
name=polyorb-snap-$change

TMPDIR=$HOME utils/make_distrib -p4 $change $name
tar=$name.tar.gz
scp $tar libre.act-europe.fr:/paris.a/httpd/html-libre/polyorb/snapshots/ \
  && rm -f $tar
