#! /bin/sh
# $Id$
#
# Build a snapshot of PolyORB from Perforce repository files.
#
# make_snapshot [-scp]
#   -scp : update snapshots directory on PolyORB's Web site.
#

scp=false

case $1 in
    -scp) scp=true; shift;;
    *) ;;
esac

name=polyorb-src

TMPDIR=$HOME utils/make_distrib -svn $name

change=`tar tzf $name.tar.gz $name/CHANGE"*" | sed 's/.*CHANGE_//'`
tar=polyorb-snap-$change.tar.gz
mv $name.tar.gz $tar
name=polyorb-snap-$change.tar.gz

if $scp; then
tar=$name.tar.gz
scp $tar libre.act-europe.fr:/paris.a/httpd/html-libre/polyorb/snapshots/ \
  && rm -f $tar
fi
