#!/bin/sh
#
# $Id$
#
# This script performs all the necessary steps to transform a checked
# out copy of PolyORB into a source tree suitable for packaging.
#
# The file MANIFEST contains the list of files to be included in this
# archive, one file per line.
#

change=
with_doc=false

###################################################
# Usage information
###################################################

usage() {
   echo "Usage: $0 [-c CHANGE] [-V version] [-D] dir"
   echo "  -c  optional CM change identifier"
   echo "  -V  optional additional version identifier"
   echo "  -D  build documentation"
   exit 1
}

set -e

###################################################
# Parse commande line
###################################################

while getopts c:V:D opt; do
  case "$opt" in
    c) change="$OPTARG" ;;
    D) with_doc=true ;;
    V) additional_version="$OPTARG" ;;
    *) usage ;;
  esac
done

shift `expr $OPTIND - 1`

if [ $# != 1 ]; then
  usage
fi

dir=$1

cd $dir

if [ ! -z "$change" ]; then
  taginfo="CHANGE_${change}"

  if [ ! -f "${taginfo}" ]; then
    LANG=C date "+Packaged from repository rev. ${change} on %c" > ${taginfo}
  fi
  echo ${taginfo} >> MANIFEST
fi

###################################################
# Update version in all files
###################################################

# sed_in_place FILE ARG...
# Apply "sed ARG..." transformation to FILE

sed_in_place() {
  oldfile=$1; shift
  newfile=$oldfile.new.$$
  sed "$@" < $oldfile > $newfile
  mv -f $newfile $oldfile
}

#
# Substitutions for information passed on the command line
#

# Additional version information (appended to the package version)

if [ ! -z "$additional_version" ]; then
  sedcmds='-e "s/^AC_INIT(\([^,]*\), *\([^,]*\), *\(.*\))/AC_INIT(\1, \2${additional_version}, \3)/"'
fi

# Subversion revision

if [ ! -z "$change" ]; then
  sedcmds="$sedcmds"' -e "s/^AM_SUBVERSION.*$/AM_SUBVERSION($change)/"'
fi

if [ ! -z "$sedcmds" ]; then
then
  eval "sed_in_place configure.ac $sedcmds"
fi

#
# Extract version number to be substituted
#

polyorb_version=`awk -F", *" '/^AC_INIT/ {print $2}' < configure.ac`

#
# Propagate version info to required files
#

for f in "README VERSION"; do
  sed_in_place $f "s/@polyorb_version@/${polyorb_version}/g"
done

###################################################
# Generating *.in files
###################################################

echo Generating auto-generated files
if [ -f support/reconfig ]
then
  sh support/reconfig -w
fi

###################################################
# Build documentation (optional)
###################################################

if $with_doc; then
  ./configure
  cd docs
  make
  cd ..
  (cat MANIFEST ; sed 's#^#docs/#' < docs/MANIFEST) | sort | uniq > MANIFEST.new
  mv -f MANIFEST.new MANIFEST
fi

echo "Adapting modes"
chmod -R og=u-w .
