//File: SSLIOP.idl
//Part of the Security Service
//OMG File: 02-03-12

#if !defined(_SSLIOP_IDL)
#define _SSLIOP_IDL

#ifdef _PRE_3_0_COMPILER_
#include <IOP.idl>
#include <Security.idl>
#pragma prefix "omg.org"
#else
import ::IOP;
import ::Security;
#endif // _PRE_3_0_COMPILER_

module SSLIOP {

#ifndef _PRE_3_0_COMPILER_
	typeprefix SSLIOP "omg.org";
#endif // _PRE_3_0_COMPILER_

	// Security mechanism SSL
	const IOP::ComponentId TAG_SSL_SEC_TRANS = 20;
	struct SSL {
		Security::AssociationOptions									target_supports;
		Security::AssociationOptions									target_requires;
		unsigned short									port;
	};
};
#endif /* _SSLIOP_IDL */
