package Idl_Fe is

   --  This package is the root package of all the adabroker
   --  front-end

   --  Its children are :
   --      - idl_fe.lexer which implements the idl lexer
   --      - idl_fe.parser which implements the idl parser
   --      - idl_fe.types which define some usefull types, including
   --  the nodes of the tree generated by the parser.
   --      - idl_fe.display_tree which defines methods to display
   --  the output of the parser

   pragma Pure;

end Idl_Fe;
