#!/usr/bin/perl

$opt = @ARGV [1];

open (IDLAC, "idlac.out") || die "Erreur d'ouverture de idlac.out";

@Tab1 = <STDIN>;
@Tab2 = <IDLAC>;
$LastTab1 = $#Tab1; 
$LastTab2 = $#Tab2; 
$i2 = 0; 
for ($i1=0; $i1 <= $LastTab1;$i1++)
{
  
  while ((@Tab1[$i1] ne @Tab2[$i2]) and ($i2<= $LastTab2))  
  {
      $i2++;
  } 
  if ($i2> $LastTab2) 
  {
      die ("iac: @Tab1[$i1]"); 
  }

  if ($opt eq "-v") 
  {
      print "iac:$Tab1[$i1]\n";
      print "idlac:$Tab2[$i2]\n";
  }    
}
