module m {
  interface int1 {
     short op1();
     attribute long attr1, attr11;
     typedef string myType1;
     const long myConstant1 = 1;
     exception myException1 {};
     struct myStruct1 {
        long  a;
	short b;
     };
     union myUnion1 switch (long) {
        case 1: case 3: long counter;
	case 2: boolean flag;
	default: long unknown;
     };
     enum Color {Red, Green, Blue};
  };
  interface int2 : int1{
     short op2();
     attribute long attr2, attr22;
  };
};

