#! /bin/sh
# $Id$

output=/infres/shalmaneser/quinot/polyorb-output

force=false
all=false

while getopts fa opt; do
  case $opt in
    f) force=true ;;
    a) all=true ;;
    *) echo "Usage: $0 [-fa]"; exit 1 ;;
  esac
done

for d in $output/*; do
  if [ ! -d $d ]; then continue; fi
  if $force || [ ! -f $d/99RESULTS ]; then
    cp $d/00PARAMETERS $d/99RESULTS
    . $d/00PARAMETERS
    for f in $d/cli*; do
      sed -n '/.*Elapsed *: \([0-9]*\.[0-9]*\)$/s//\1/p' < $f
    done | awk '{ sum += $1; sqsum += $1 * $1 }
                 END { if (sum > 0 && NR == '"$nmax"') {
                         print "status=OK"
                         avg = sum / NR;
                         printf "moy=%.12g\nect=%.12g\n",
                           (sum / NR), sqrt(sqsum/NR - (avg * avg))
                       } else { print "status=FAILED"; } }' >> $d/99RESULTS
  fi
  if $all || grep status=OK $d/99RESULTS > /dev/null; then
    cat $d/99RESULTS
    echo "----------"
  fi
done
