module DSA_Common {
   interface Penpal_Type;

   interface Penpal_Type {
      void initialize (in string Name);
      string name_of ();
      void new_message (in string Sender, in string Message);
   };
};
