module AnnApp01 {

   @range((-1), 1) @nested
   typedef short around_zero;

   enum myenum_t {
      zero,
      @default_literal one
   };

   struct mystruct_t {
      @key long k;
      @key myenum_t e;
      around_zero az;
   };

};

