interface test_all_optims {

   typedef long sixteenKb[64][64];

   sixteenKb echoSixteenKb00 (in sixteenKb data) ;
   sixteenKb echoSixteenKb01 (in sixteenKb data) ;
   sixteenKb echoSixteenKb02 (in sixteenKb data) ;
   sixteenKb echoSixteenKb03 (in sixteenKb data) ;
   sixteenKb echoSixteenKb04 (in sixteenKb data) ;
   sixteenKb echoSixteenKb05 (in sixteenKb data) ;
   sixteenKb echoSixteenKb06 (in sixteenKb data) ;
   sixteenKb echoSixteenKb07 (in sixteenKb data) ;
   sixteenKb echoSixteenKb08 (in sixteenKb data) ;
   sixteenKb echoSixteenKb09 (in sixteenKb data) ;
   sixteenKb echoSixteenKb10 (in sixteenKb data) ;
   sixteenKb echoSixteenKb11 (in sixteenKb data) ;
   sixteenKb echoSixteenKb12 (in sixteenKb data) ;
   sixteenKb echoSixteenKb13 (in sixteenKb data) ;
   sixteenKb echoSixteenKb14 (in sixteenKb data) ;
   sixteenKb echoSixteenKb15 (in sixteenKb data) ;
   sixteenKb echoSixteenKb16 (in sixteenKb data) ;
   sixteenKb echoSixteenKb17 (in sixteenKb data) ;
   sixteenKb echoSixteenKb18 (in sixteenKb data) ;
   sixteenKb echoSixteenKb19 (in sixteenKb data) ;
   sixteenKb echoSixteenKb20 (in sixteenKb data) ;
   sixteenKb echoSixteenKb21 (in sixteenKb data) ;
   sixteenKb echoSixteenKb22 (in sixteenKb data) ;
   sixteenKb echoSixteenKb23 (in sixteenKb data) ;
   sixteenKb echoSixteenKb24 (in sixteenKb data) ;
   sixteenKb echoSixteenKb25 (in sixteenKb data) ;
   sixteenKb echoSixteenKb26 (in sixteenKb data) ;
   sixteenKb echoSixteenKb27 (in sixteenKb data) ;
   sixteenKb echoSixteenKb28 (in sixteenKb data) ;
   sixteenKb echoSixteenKb29 (in sixteenKb data) ;
   sixteenKb echoSixteenKb30 (in sixteenKb data) ;
   sixteenKb echoSixteenKb31 (in sixteenKb data) ;
   sixteenKb echoSixteenKb32 (in sixteenKb data) ;
   sixteenKb echoSixteenKb33 (in sixteenKb data) ;
   sixteenKb echoSixteenKb34 (in sixteenKb data) ;
   sixteenKb echoSixteenKb35 (in sixteenKb data) ;
   sixteenKb echoSixteenKb36 (in sixteenKb data) ;
   sixteenKb echoSixteenKb37 (in sixteenKb data) ;
   sixteenKb echoSixteenKb38 (in sixteenKb data) ;
   sixteenKb echoSixteenKb39 (in sixteenKb data) ;
   sixteenKb echoSixteenKb40 (in sixteenKb data) ;
   sixteenKb echoSixteenKb41 (in sixteenKb data) ;
   sixteenKb echoSixteenKb42 (in sixteenKb data) ;
   sixteenKb echoSixteenKb43 (in sixteenKb data) ;
   sixteenKb echoSixteenKb44 (in sixteenKb data) ;
   sixteenKb echoSixteenKb45 (in sixteenKb data) ;
   sixteenKb echoSixteenKb46 (in sixteenKb data) ;
   sixteenKb echoSixteenKb47 (in sixteenKb data) ;
   sixteenKb echoSixteenKb48 (in sixteenKb data) ;
   sixteenKb echoSixteenKb49 (in sixteenKb data) ;
   sixteenKb echoSixteenKb50 (in sixteenKb data) ;
   sixteenKb echoSixteenKb51 (in sixteenKb data) ;
   sixteenKb echoSixteenKb52 (in sixteenKb data) ;
   sixteenKb echoSixteenKb53 (in sixteenKb data) ;
   sixteenKb echoSixteenKb54 (in sixteenKb data) ;
   sixteenKb echoSixteenKb55 (in sixteenKb data) ;
   sixteenKb echoSixteenKb56 (in sixteenKb data) ;
   sixteenKb echoSixteenKb57 (in sixteenKb data) ;
   sixteenKb echoSixteenKb58 (in sixteenKb data) ;
   sixteenKb echoSixteenKb59 (in sixteenKb data) ;
   sixteenKb echoSixteenKb60 (in sixteenKb data) ;
   sixteenKb echoSixteenKb61 (in sixteenKb data) ;
   sixteenKb echoSixteenKb62 (in sixteenKb data) ;
   sixteenKb echoSixteenKb63 (in sixteenKb data) ;
   sixteenKb echoSixteenKb64 (in sixteenKb data) ;
   sixteenKb echoSixteenKb65 (in sixteenKb data) ;
   sixteenKb echoSixteenKb66 (in sixteenKb data) ;
   sixteenKb echoSixteenKb67 (in sixteenKb data) ;
   sixteenKb echoSixteenKb68 (in sixteenKb data) ;
   sixteenKb echoSixteenKb69 (in sixteenKb data) ;
   sixteenKb echoSixteenKb70 (in sixteenKb data) ;
   sixteenKb echoSixteenKb71 (in sixteenKb data) ;
   sixteenKb echoSixteenKb72 (in sixteenKb data) ;
   sixteenKb echoSixteenKb73 (in sixteenKb data) ;
   sixteenKb echoSixteenKb74 (in sixteenKb data) ;
   sixteenKb echoSixteenKb75 (in sixteenKb data) ;
   sixteenKb echoSixteenKb76 (in sixteenKb data) ;
   sixteenKb echoSixteenKb77 (in sixteenKb data) ;
   sixteenKb echoSixteenKb78 (in sixteenKb data) ;
   sixteenKb echoSixteenKb79 (in sixteenKb data) ;
   sixteenKb echoSixteenKb80 (in sixteenKb data) ;
   sixteenKb echoSixteenKb81 (in sixteenKb data) ;
   sixteenKb echoSixteenKb82 (in sixteenKb data) ;
   sixteenKb echoSixteenKb83 (in sixteenKb data) ;
   sixteenKb echoSixteenKb84 (in sixteenKb data) ;
   sixteenKb echoSixteenKb85 (in sixteenKb data) ;
   sixteenKb echoSixteenKb86 (in sixteenKb data) ;
   sixteenKb echoSixteenKb87 (in sixteenKb data) ;
   sixteenKb echoSixteenKb88 (in sixteenKb data) ;
   sixteenKb echoSixteenKb89 (in sixteenKb data) ;
   sixteenKb echoSixteenKb90 (in sixteenKb data) ;
   sixteenKb echoSixteenKb91 (in sixteenKb data) ;
   sixteenKb echoSixteenKb92 (in sixteenKb data) ;
   sixteenKb echoSixteenKb93 (in sixteenKb data) ;
   sixteenKb echoSixteenKb94 (in sixteenKb data) ;
   sixteenKb echoSixteenKb95 (in sixteenKb data) ;
   sixteenKb echoSixteenKb96 (in sixteenKb data) ;
   sixteenKb echoSixteenKb97 (in sixteenKb data) ;
   sixteenKb echoSixteenKb98 (in sixteenKb data) ;
   sixteenKb echoSixteenKb99 (in sixteenKb data) ;
};

