//testsubgroup a valuetype supporting an interface
//tsgdescr "Testing  a   valuetype supporting (and interface derived from) an abstract interface"

abstract interface AbsItf {
  short op1();
};
interface Itfderiv: AbsItf {
  short op2();
};
valuetype Val supports AbsItf {
  short op3();
};
