//testsubgroup a valuetype supporting an interface
//tsgdescr "Testing  a  (abstract) valuetype supporting an interface"

interface Itf {
  short op1();
  long op2();

};

abstract valuetype AbsVal supports Itf {
  short op3();
};

valuetype Val: AbsVal {
  public short shrMbr;
};
