//testsubgroup a valuetype supporting an interface
//tsgdescr "Testing  a  valuetype supporting an interface"

interface Itf {
  short op1();
  long op2();

};

valuetype Val supports Itf {
  public short shtMber;
};
