.TH PO_NAMES 1 "December 1, 2003" "PolyORB team" "PolyORB documentation"

.SH NAME
po_names \- PolyORB name server

.SH SYNOPSIS
.B po_names

.SH DESCRIPTION
.B po_names
is an implementation of CORBA CosNaming service built on top of
.B PolyORB.

.SH ENVIRONMENT
.B po_names
uses the
.I POLYORB_CONF
environment variable. See
.BR polyorb (7)
for more information.

.SH AUTHORS
The \fIPolyORB\fP team, polyorb-devel@lists.adacore.com.

.SH SEE ALSO
.BR polyorb (7)
.br
The \fIPolyORB\fP WWW page,
.B
http://libre.adacore.com/polyorb/
.b
