#! /bin/sh

setgcc () {
  for a in adagcc gnatgcc
  do
    if f=`which $a` && [ -x "$f" ]
    then
      ADAGCC="$a"
      return
    fi
  done
  ADAGCC=gcc
}

setfile () {
  while [ "$#" -gt 1 ]
  do
    shift
  done
  file="$1"
}

setecho () {
  if [ -x /usr/ucb/echo ]
  then
    echo=/usr/ucb/echo
  else
    echo=echo
  fi
}

if [ ! -x "$ADAGCC" ]
then
  setgcc
fi
setfile "$@"
setecho

########## Start processing.

$echo -n "Compiling $file"

case $file in
  droopi-orb-thread_pool.adb|droopi-protected_objects.adb)
    echo " without gnat.adc"
    mv -f gnat.adc gnat.adc-
    $ADAGCC "$@"
    rc=$!
    mv -f gnat.adc- gnat.adc
    exit $rc
    ;;
  *)
    echo ""
    exec $ADAGCC "$@"
    ;;
esac

