#
# Common Makefile fragments for the PolyORB runtime library
# $Id$
#

CFLAGS+=	$(STD_CFLAGS)

depend:
	for d in $(SUBDIRS);do ( \
		if [ "$$d" != "." ]; then \
		  cd $$d; \
		  ${MAKE} depend; \
		fi \
	); done; \
	${MAKE} depend-local

depend-local: all
	$(top_srcdir)/support/mkdep "$(srcdir)" "$(builddir)" "$(top_srcdir)" "$(top_builddir)" $(ADAFLAGS) $(ALL_GEN_FILES)

include $(top_srcdir)/Makefile.common
