with PolyORB.POA_Types;     use PolyORB.POA_Types;


package PolyORB.POA_Policies.Lifespan_Policy is

   type LifespanPolicy is abstract new Policy with null record;
   subtype Lifespan_Policy is LifespanPolicy;
   type LifespanPolicy_Access is access all LifespanPolicy'Class;
   subtype Lifespan_Policy_Access is LifespanPolicy_Access;

   function Create return LifespanPolicy_Access is abstract;
   --  The real creation function that has to be implemented for each
   --  possible Policy

   function Get_Time_Stamp (P  : LifespanPolicy;
                            OA : PolyORB.POA_Types.Obj_Adapter_Access)
                           return Time_Stamp is abstract;

   procedure Ensure_Lifespan (P     : LifespanPolicy;
                              OA    : PolyORB.POA_Types.Obj_Adapter_Access;
                              U_Oid : Unmarshalled_Oid_Access)
      is abstract;
   --  PERSISTENT:
   --  Ensure that the Oid has been generated by the current instantiation
   --  of the POA.
   --  If not, raises a BAD_PARAM exception.
   --  TRANSIENT:
   --  Does nothing.

   procedure Free
     (P   : in     LifespanPolicy;
      Ptr : in out Policy_Access) is abstract;

end PolyORB.POA_Policies.Lifespan_Policy;
