------------------------------------------------------------------------------
--                                                                          --
--                           POLYORB COMPONENTS                             --
--                                                                          --
--                POLYORB.POA_POLICIES.ID_ASSIGNMENT_POLICY                 --
--                                                                          --
--                                 S p e c                                  --
--                                                                          --
--                Copyright (C) 2001 Free Software Fundation                --
--                                                                          --
-- PolyORB is free software; you  can  redistribute  it and/or modify it    --
-- under terms of the  GNU General Public License as published by the  Free --
-- Software Foundation;  either version 2,  or (at your option)  any  later --
-- version. PolyORB is distributed  in the hope that it will be  useful,    --
-- but WITHOUT ANY WARRANTY;  without even the implied warranty of MERCHAN- --
-- TABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public --
-- License  for more details.  You should have received  a copy of the GNU  --
-- General Public License distributed with PolyORB; see file COPYING. If    --
-- not, write to the Free Software Foundation, 59 Temple Place - Suite 330, --
-- Boston, MA 02111-1307, USA.                                              --
--                                                                          --
-- As a special exception,  if other files  instantiate  generics from this --
-- unit, or you link  this unit with other files  to produce an executable, --
-- this  unit  does not  by itself cause  the resulting  executable  to  be --
-- covered  by the  GNU  General  Public  License.  This exception does not --
-- however invalidate  any other reasons why  the executable file  might be --
-- covered by the  GNU Public License.                                      --
--                                                                          --
--              PolyORB is maintained by ENST Paris University.             --
--                                                                          --
------------------------------------------------------------------------------

--  $Id$

with PolyORB.POA_Types;     use PolyORB.POA_Types;

package PolyORB.POA_Policies.Id_Assignment_Policy is

   type IdAssignmentPolicy is abstract new Policy with null record;
   subtype Id_Assignment_Policy is IdAssignmentPolicy;
   type IdAssignmentPolicy_Access is access all IdAssignmentPolicy'Class;
   subtype Id_Assignment_Policy_Access is IdAssignmentPolicy_Access;

   function Is_System (P : IdAssignmentPolicy) return Boolean
      is abstract;
   --  Checks if the current policy is able to create ObjectIds
   --  (System_Id policy)

   function Assign_Object_Identifier
     (Self   : IdAssignmentPolicy;
      OA     : PolyORB.POA_Types.Obj_Adapter_Access;
      Hint   : Object_Id_Access)
     return Unmarshalled_Oid
   is abstract;

   procedure Ensure_Oid_Origin
     (Self  : IdAssignmentPolicy;
      U_Oid : Unmarshalled_Oid)
      is abstract;
   --  Checks if the given Oid has been generated by the system
   --  or by the user, according to the policy.

end PolyORB.POA_Policies.Id_Assignment_Policy;
