//File: CosExternalizationContainment.idl
//Part of the Externalization Service
// modified from version 1.0 to use CosStream module 
//     instead of CosCompoundExternalization

#ifndef _COS_EXTERNALIZATION_CONTAINMENT_IDL_
#define _COS_EXTERNALIZATION_CONTAINMENT_IDL_

#include <CosContainment.idl>
#include <CosStream.idl>

#pragma prefix "omg.org"

module CosExternalizationContainment {

	interface Relationship : 
		CosStream::Relationship,
		CosContainment::Relationship {};

	interface ContainsRole : 
		CosStream::Role,
		CosContainment::ContainsRole {};

	interface ContainedInRole : 
		CosStream::Role,
		CosContainment::ContainedInRole {};
};
#endif /* ifndef _COS_EXTERNALIZATION_CONTAINMENT_IDL_*/
