//File: CosExternalizationReference.idl
//Part of the Externalization Service
// modified from version 1.0 to use CosStream module 
//     instead of CosCompoundExternalization
//OMG File: 98-10-11

#ifndef _COS_EXTERNALIZATION_REFERENCE_IDL_
#define _COS_EXTERNALIZATION_REFERENCE_IDL_

#ifdef _PRE_3_0_COMPILER_
#include <CosReference.idl>
#include <CosStream.idl>
#pragma prefix "omg.org"
#else
import ::CosReference;
import ::CosStream;
#endif // _PRE_3_0_COMPILER_

module CosExternalizationReference {

#ifndef _PRE_3_0_COMPILER_
	typeprefix CosExternalizationReference "omg.org";
#endif // _PRE_3_0_COMPILER_

	interface Relationship : 
		CosStream::Relationship,
		CosReference::Relationship {};

	interface ReferencesRole : 
		CosStream::Role,
		CosReference::ReferencesRole {};

	interface ReferencedByRole : 
		CosStream::Role,
		CosReference::ReferencedByRole {};
};
#endif /* ifndef _COS_EXTERNALIZATION_REFERENCE_IDL_ */
