// IDL-Spec for testgroup: valuetype
// Purpose: Data member in a valuetype

valuetype Val {
  //state
  private short shtMbr;
  public unsigned short ushtMbr;
  public long longMbr;
  private unsigned long ulongMbr;
  private long long longlongMbr;
  public unsigned long long ulonglongMbr;
  public boolean boolMbr;
  private octet octetMbr;
  public char charMbr;
  private wchar wcharMbr;
  public float floatMbr;
  private double doubleMbr;
  public string stringMbr;
  private wstring wstringMbr;
  //initializer
  factory create_publ(in unsigned short ushtM,
                      in long longM,
                      in unsigned long long ulonglongM,
                      in boolean boolM,
                      in char charM,
                      in float floatM,
                      in string stringM);
  factory create_private(in short shtM,
                         in unsigned long ulongM,
                         in long long longlongM,
                         in octet octetM,
                         in wchar wcharM,
                         in double doubleM,
                         in wstring wstringM);
};
