// File: BiDirPolicy.idl
// From CORBA 3.0: Chapter 15, General Inter-ORB Protocol

#ifndef _BIDIR_POLICY_IDL_
#define _BIDIR_POLICY_IDL_

#ifdef _PRE_3_0_COMPILER_ 
#pragma prefix "omg.org"

#include <orb.idl>
#else
//PolyORB:NI:import ::CORBA;
#endif // _PRE_3_0_COMPILER_

//PolyORB:NI:// Self contained module for Bi-directional GIOP policy
//PolyORB:NI:module BiDirPolicy {
//PolyORB:NI:
//PolyORB:NI:#ifndef _PRE_3_0_COMPILER_ 
//PolyORB:NI:    typeprefix BiDirPolicy "omg.org";
//PolyORB:NI:#endif // _PRE_3_0_COMPILER_
//PolyORB:NI:
//PolyORB:NI:    typedef unsigned short BidirectionalPolicyValue;
//PolyORB:NI:
//PolyORB:NI:    const BidirectionalPolicyValue NORMAL               = 0;
//PolyORB:NI:    const BidirectionalPolicyValue BOTH                 = 1;
//PolyORB:NI:    const CORBA::PolicyType BIDIRECTIONAL_POLICY_TYPE   = 37;
//PolyORB:NI:
//PolyORB:NI:    interface BidirectionalPolicy : CORBA::Policy {
//PolyORB:NI:        readonly attribute BidirectionalPolicyValue value;
//PolyORB:NI:    };
//PolyORB:NI:};

#endif // _BIDIR_POLICY_IDL_
