interface vehicle {
  attribute string mark;
  boolean can_drive(in unsigned short age) ;
  typedef string model;
};

interface weapon {
  typedef string name;
void shoot (in long ranges);
};

interface tank : vehicle, weapon {
string move(in string fast); 
};
