interface vehicle {
  attribute string mark;
  struct dist1{
	long longueur[2];
	long largeur;
  };
  boolean can_drive(in unsigned short age) ;
  typedef string model;
};

interface weapon {
  typedef string name;
  struct dist{
	long longueur[3];
	long largeur;
  };
  void shoot (in dist ranges);
};

interface tank : vehicle, weapon {
string move(in dist wide); 
};


