//File: CosContainment.idl
//Part of the Externalization Service
//OMG File: 98-10-31

#ifndef _COS_CONTAINMENT_IDL_
#define _COS_CONTAINMENT_IDL_

#ifdef _PRE_3_0_COMPILER_
#include <CosGraphs.idl>
#pragma prefix "omg.org"
#else
import ::CosGraphs;
#endif // _PRE_3_0_COMPILER_

module CosContainment {

#ifndef _PRE_3_0_COMPILER_
	typeprefix CosContainment "omg.org";
#endif // _PRE_3_0_COMPILER_

 	interface Relationship : CosRelationships::Relationship {};

 	interface ContainsRole : CosGraphs::Role {};

 	interface ContainedInRole : CosGraphs::Role {};

};
#endif /* ifndef _COS_CONTAINMENT_IDL_ */
