###----------------------------------------------------------------------
### File    : makefile
### Author  : Thomas Quinot <quinot@shalmaneser.enst.fr>
### Purpose : Makefile for application build_manager.
### Created : 24 Apr 2000 by Thomas Quinot <quinot@shalmaneser.enst.fr>
###----------------------------------------------------------------------

MAKE = make

######################################################################

def:
	(cd src ; $(MAKE))

clean:
	(cd src ; $(MAKE) clean)

