.TH AB_GNOME 1 "June 30, 2000" "AdaBroker team" "AdaBroker documentation"

.SH NAME
ab_gnome \- interaction between AdaBroker and GNOME

.SH SYNOPSIS
.B ab_gnome
.I command

.SH DESCRIPTION
.B ab_gnome
sets up the environment to let a program developed with AdaBroker access
GNOME naming service.

.SH EXAMPLE
You can use the
.B test_naming
program from the AdaBroker distribution and have it use GNOME naming service
by using:
.RS
.B ab_gnome test_naming \-i
.RE

.SH AUTHORS
The AdaBroker team, adabroker@adabroker.eu.org

.SH SEE ALSO
.BR adabroker (7)
.BR gnome (1)
