.TH AB_NAMES 1 "June 30, 2000" "AdaBroker team" "AdaBroker documentation"

.SH NAME
ab_names \- AdaBroker name server

.SH SYNOPSIS
.B ab_names

.SH DESCRIPTION
.B ab_names
is an implementation of CORBA CosNaming service built on top of
.B AdaBroker.

.SH ENVIRONMENT
.B ab_names
uses the
.I ADABROKER_CONFIG
and
.I ADABROKER_NAMING_PORT
environment variables. See
.BR adabroker (7)
for more information.

.SH AUTHORS
The AdaBroker team, adabroker@adabroker.eu.org

.SH SEE ALSO
.BR adabroker (7)
.br
The AdaBroker WWW page,
.B
http://adabroker.eu.org/
.b
