//testsubgroup typedef_inheritance
//tsgdescr "Testing scope of typedef declarations with the valuetype inheritance"

valuetype AVal {
	typedef long TypeLong;
	public TypeLong Mbr1;
};
valuetype BVal : AVal {
	public TypeLong Mbr2;
};

valuetype CVal : BVal {
	public TypeLong Mbr3;
};
