
import ::PortableServer;

module Test {

    interface Echo {
        string Echo_String (in string Value);
    };

    interface _Factory {
        typedef sequence<Echo> EchoSequence;

        void Preallocate (in long Count);
        EchoSequence Create_References (in long Count);

        void Shutdown ();
    };

    local interface Activator : PortableServer::ServantActivator { };

};
