//
// Copyright (c) 1997 X/Open Company Ltd., A member of The Open Group.
//
// All rights reserved. No part of this source code may be reproduced,
// stored in a retrieval system, or transmitted, in any form or by any
// means, electronic, mechanical, photocopying, recording or otherwise,
// except as stated in the end-user licence agreement, without the prior
// permission of the copyright owners.
//
// Developed for X/Open by ApTest Ireland Limited.
//
// Project: CORVAL2
//


interface Banana;

struct Corn{
  short Eddo;
  Banana Yam;
  long Rasin;
  float Peach;
};

interface Banana;

interface Apple {
  attribute Banana Peanuts;
};

interface Banana {
  void Orange(in Banana p1);
  void Basil(out Banana p1);
  void VineTomatoes(inout Banana p1);
};

interface idlServer : Apple, Banana {
  idlServer Lemon(in Corn p1);
};

