
#  $Id$

#  This is a NT specific makefile. It is used to build GLADE under NT.
#
#  USAGE
#
#  To build GLADE   : make -f workspace/makefile.nt build
#  To install GLADE : make -f workspace/makefile.nt install
#

.SILENT:

#  right now only i386-pc-cygwin32 config name is recognized.
#  this variable is not used. (FIXME)
CONFIG_NAME = i686-pc-mingw32

#  (to be changed) this is the directory where GLADE must be installed.
INSTALL_DIR=/usr

######## AFTER THIS LINE YOU SHOULD NOT HAVE TO CHANGE ANYTHING  ###########


DIST_DIR=./Dist
DIST_MAKEFILE=$(DIST_DIR)/Makefile.in

GARLIC_DIR=./Garlic
GARLIC_MAKEFILE=$(GARLIC_DIR)/Makefile.in
GARLIC_TCP=$(GARLIC_DIR)/s-gartcp.adb

all:
	echo ""
	echo "USAGE"
	echo ""
	echo "make -f workspace/makefile.nt build   : to build GLADE under NT"
	echo "make -f workspace/makefile.nt install : to install GLADE"
	echo ""
	echo "The install directory is " $(INSTALL_DIR)
	echo ""
	echo "You must edit the makefile to change the install directory"
	echo " or add INSTALL_DIR=/somedir/somesubdir at the make command"
	echo ""

build: fix_distrib build_glade

fix_distrib: fix_gartcp

#  under NT we must use Recv (instead of Read) and Send (instead of Write) on
#  a socket.
fix_gartcp:
	mv $(GARLIC_TCP) $(GARLIC_TCP).orig
	sed 's/C_Read/C_Recv/g;s/C_Write/C_Send/g;s/, Rest);/, Rest, 0);/g' \
		$(GARLIC_TCP).orig > $(GARLIC_TCP)

build_glade:
	./configure --prefix=$(INSTALL_DIR)
	make
force:

install: force
	make install
