//File: CosTypedEventComm.idl
//Part of the Event Service

#ifndef _COS_TYPED_EVENT_COMM_IDL_
#define _COS_TYPED_EVENT_COMM_IDL_

#ifdef _PRE_3_0_COMPILER_
#include <CosEventComm.idl>
#pragma prefix "omg.org"
#else
import ::CosEventComm;
#endif // _PRE_3_0_COMPILER_

module CosTypedEventComm {

#ifndef _PRE_3_0_COMPILER_
	typeprefix CosTypedEventComm "omg.org";
#endif // _PRE_3_0_COMPILER_

	interface TypedPushConsumer : CosEventComm::PushConsumer {
		Object get_typed_consumer(); 
	};

	interface TypedPullSupplier : CosEventComm::PullSupplier { 		 
		Object get_typed_supplier();
	};

}; 

#endif /* ifndef _COS_TYPED_EVENT_COMM_IDL_ */
